// Source: kongvut/thai-province-data (MIT License)
// https://github.com/kongvut/thai-province-data
// Fetched from data/raw/districts.json, cross-referenced with data/raw/provinces.json

export interface District {
  code: string;
  nameTh: string;
  nameEn: string;
  provinceCode: string;
}

export const DISTRICTS: District[] = [
  { code: "1001", nameTh: "เขตพระนคร", nameEn: "Khet Phra Nakhon", provinceCode: "10" },
  { code: "1002", nameTh: "เขตดุสิต", nameEn: "Khet Dusit", provinceCode: "10" },
  { code: "1003", nameTh: "เขตหนองจอก", nameEn: "Khet Nong Chok", provinceCode: "10" },
  { code: "1004", nameTh: "เขตบางรัก", nameEn: "Khet Bang Rak", provinceCode: "10" },
  { code: "1005", nameTh: "เขตบางเขน", nameEn: "Khet Bang Khen", provinceCode: "10" },
  { code: "1006", nameTh: "เขตบางกะปิ", nameEn: "Khet Bang Kapi", provinceCode: "10" },
  { code: "1007", nameTh: "เขตปทุมวัน", nameEn: "Khet Pathum Wan", provinceCode: "10" },
  { code: "1008", nameTh: "เขตป้อมปราบศัตรูพ่าย", nameEn: "Khet Pom Prap Sattru Phai", provinceCode: "10" },
  { code: "1009", nameTh: "เขตพระโขนง", nameEn: "Khet Phra Khanong", provinceCode: "10" },
  { code: "1010", nameTh: "เขตมีนบุรี", nameEn: "Khet Min Buri", provinceCode: "10" },
  { code: "1011", nameTh: "เขตลาดกระบัง", nameEn: "Khet Lat Krabang", provinceCode: "10" },
  { code: "1012", nameTh: "เขตยานนาวา", nameEn: "Khet Yan Nawa", provinceCode: "10" },
  { code: "1013", nameTh: "เขตสัมพันธวงศ์", nameEn: "Khet Samphanthawong", provinceCode: "10" },
  { code: "1014", nameTh: "เขตพญาไท", nameEn: "Khet Phaya Thai", provinceCode: "10" },
  { code: "1015", nameTh: "เขตธนบุรี", nameEn: "Khet Thon Buri", provinceCode: "10" },
  { code: "1016", nameTh: "เขตบางกอกใหญ่", nameEn: "Khet Bangkok Yai", provinceCode: "10" },
  { code: "1017", nameTh: "เขตห้วยขวาง", nameEn: "Khet Huai Khwang", provinceCode: "10" },
  { code: "1018", nameTh: "เขตคลองสาน", nameEn: "Khet Khlong San", provinceCode: "10" },
  { code: "1019", nameTh: "เขตตลิ่งชัน", nameEn: "Khet Taling Chan", provinceCode: "10" },
  { code: "1020", nameTh: "เขตบางกอกน้อย", nameEn: "Khet Bangkok Noi", provinceCode: "10" },
  { code: "1021", nameTh: "เขตบางขุนเทียน", nameEn: "Khet Bang Khun Thian", provinceCode: "10" },
  { code: "1022", nameTh: "เขตภาษีเจริญ", nameEn: "Khet Phasi Charoen", provinceCode: "10" },
  { code: "1023", nameTh: "เขตหนองแขม", nameEn: "Khet Nong Khaem", provinceCode: "10" },
  { code: "1024", nameTh: "เขตราษฎร์บูรณะ", nameEn: "Khet Rat Burana", provinceCode: "10" },
  { code: "1025", nameTh: "เขตบางพลัด", nameEn: "Khet Bang Phlat", provinceCode: "10" },
  { code: "1026", nameTh: "เขตดินแดง", nameEn: "Khet Din Daeng", provinceCode: "10" },
  { code: "1027", nameTh: "เขตบึงกุ่ม", nameEn: "Khet Bueng Kum", provinceCode: "10" },
  { code: "1028", nameTh: "เขตสาทร", nameEn: "Khet Sathon", provinceCode: "10" },
  { code: "1029", nameTh: "เขตบางซื่อ", nameEn: "Khet Bang Sue", provinceCode: "10" },
  { code: "1030", nameTh: "เขตจตุจักร", nameEn: "Khet Chatuchak", provinceCode: "10" },
  { code: "1031", nameTh: "เขตบางคอแหลม", nameEn: "Khet Bang Kho Laem", provinceCode: "10" },
  { code: "1032", nameTh: "เขตประเวศ", nameEn: "Khet Prawet", provinceCode: "10" },
  { code: "1033", nameTh: "เขตคลองเตย", nameEn: "Khet Khlong Toei", provinceCode: "10" },
  { code: "1034", nameTh: "เขตสวนหลวง", nameEn: "Khet Suan Luang", provinceCode: "10" },
  { code: "1035", nameTh: "เขตจอมทอง", nameEn: "Khet Chom Thong", provinceCode: "10" },
  { code: "1036", nameTh: "เขตดอนเมือง", nameEn: "Khet Don Mueang", provinceCode: "10" },
  { code: "1037", nameTh: "เขตราชเทวี", nameEn: "Khet Ratchathewi", provinceCode: "10" },
  { code: "1038", nameTh: "เขตลาดพร้าว", nameEn: "Khet Lat Phrao", provinceCode: "10" },
  { code: "1039", nameTh: "เขตวัฒนา", nameEn: "Khet Watthana", provinceCode: "10" },
  { code: "1040", nameTh: "เขตบางแค", nameEn: "Khet Bang Khae", provinceCode: "10" },
  { code: "1041", nameTh: "เขตหลักสี่", nameEn: "Khet Lak Si", provinceCode: "10" },
  { code: "1042", nameTh: "เขตสายไหม", nameEn: "Khet Sai Mai", provinceCode: "10" },
  { code: "1043", nameTh: "เขตคันนายาว", nameEn: "Khet Khan Na Yao", provinceCode: "10" },
  { code: "1044", nameTh: "เขตสะพานสูง", nameEn: "Khet Saphan Sung", provinceCode: "10" },
  { code: "1045", nameTh: "เขตวังทองหลาง", nameEn: "Khet Wang Thonglang", provinceCode: "10" },
  { code: "1046", nameTh: "เขตคลองสามวา", nameEn: "Khet Khlong Sam Wa", provinceCode: "10" },
  { code: "1047", nameTh: "เขตบางนา", nameEn: "Khet Bang Na", provinceCode: "10" },
  { code: "1048", nameTh: "เขตทวีวัฒนา", nameEn: "Khet Thawi Watthana", provinceCode: "10" },
  { code: "1049", nameTh: "เขตทุ่งครุ", nameEn: "Khet Thung Khru", provinceCode: "10" },
  { code: "1050", nameTh: "เขตบางบอน", nameEn: "Khet Bang Bon", provinceCode: "10" },
  { code: "1101", nameTh: "เมืองสมุทรปราการ", nameEn: "Mueang Samut Prakan", provinceCode: "11" },
  { code: "1102", nameTh: "บางบ่อ", nameEn: "Bang Bo", provinceCode: "11" },
  { code: "1103", nameTh: "บางพลี", nameEn: "Bang Phli", provinceCode: "11" },
  { code: "1104", nameTh: "พระประแดง", nameEn: "Phra Pradaeng", provinceCode: "11" },
  { code: "1105", nameTh: "พระสมุทรเจดีย์", nameEn: "Phra Samut Chedi", provinceCode: "11" },
  { code: "1106", nameTh: "บางเสาธง", nameEn: "Bang Sao Thong", provinceCode: "11" },
  { code: "1201", nameTh: "เมืองนนทบุรี", nameEn: "Mueang Nonthaburi", provinceCode: "12" },
  { code: "1202", nameTh: "บางกรวย", nameEn: "Bang Kruai", provinceCode: "12" },
  { code: "1203", nameTh: "บางใหญ่", nameEn: "Bang Yai", provinceCode: "12" },
  { code: "1204", nameTh: "บางบัวทอง", nameEn: "Bang Bua Thong", provinceCode: "12" },
  { code: "1205", nameTh: "ไทรน้อย", nameEn: "Sai Noi", provinceCode: "12" },
  { code: "1206", nameTh: "ปากเกร็ด", nameEn: "Pak Kret", provinceCode: "12" },
  { code: "1301", nameTh: "เมืองปทุมธานี", nameEn: "Mueang Pathum Thani", provinceCode: "13" },
  { code: "1302", nameTh: "คลองหลวง", nameEn: "Khlong Luang", provinceCode: "13" },
  { code: "1303", nameTh: "ธัญบุรี", nameEn: "Thanyaburi", provinceCode: "13" },
  { code: "1304", nameTh: "หนองเสือ", nameEn: "Nong Suea", provinceCode: "13" },
  { code: "1305", nameTh: "ลาดหลุมแก้ว", nameEn: "Lat Lum Kaeo", provinceCode: "13" },
  { code: "1306", nameTh: "ลำลูกกา", nameEn: "Lam Luk Ka", provinceCode: "13" },
  { code: "1307", nameTh: "สามโคก", nameEn: "Sam Khok", provinceCode: "13" },
  { code: "1401", nameTh: "พระนครศรีอยุธยา", nameEn: "Phra Nakhon Si Ayutthaya", provinceCode: "14" },
  { code: "1402", nameTh: "ท่าเรือ", nameEn: "Tha Ruea", provinceCode: "14" },
  { code: "1403", nameTh: "นครหลวง", nameEn: "Nakhon Luang", provinceCode: "14" },
  { code: "1404", nameTh: "บางไทร", nameEn: "Bang Sai", provinceCode: "14" },
  { code: "1405", nameTh: "บางบาล", nameEn: "Bang Ban", provinceCode: "14" },
  { code: "1406", nameTh: "บางปะอิน", nameEn: "Bang Pa-in", provinceCode: "14" },
  { code: "1407", nameTh: "บางปะหัน", nameEn: "Bang Pahan", provinceCode: "14" },
  { code: "1408", nameTh: "ผักไห่", nameEn: "Phak Hai", provinceCode: "14" },
  { code: "1409", nameTh: "ภาชี", nameEn: "Phachi", provinceCode: "14" },
  { code: "1410", nameTh: "ลาดบัวหลวง", nameEn: "Lat Bua Luang", provinceCode: "14" },
  { code: "1411", nameTh: "วังน้อย", nameEn: "Wang Noi", provinceCode: "14" },
  { code: "1412", nameTh: "เสนา", nameEn: "Sena", provinceCode: "14" },
  { code: "1413", nameTh: "บางซ้าย", nameEn: "Bang Sai", provinceCode: "14" },
  { code: "1414", nameTh: "อุทัย", nameEn: "Uthai", provinceCode: "14" },
  { code: "1415", nameTh: "มหาราช", nameEn: "Maha Rat", provinceCode: "14" },
  { code: "1416", nameTh: "บ้านแพรก", nameEn: "Ban Phraek", provinceCode: "14" },
  { code: "1501", nameTh: "เมืองอ่างทอง", nameEn: "Mueang Ang Thong", provinceCode: "15" },
  { code: "1502", nameTh: "ไชโย", nameEn: "Chaiyo", provinceCode: "15" },
  { code: "1503", nameTh: "ป่าโมก", nameEn: "Pa Mok", provinceCode: "15" },
  { code: "1504", nameTh: "โพธิ์ทอง", nameEn: "Pho Thong", provinceCode: "15" },
  { code: "1505", nameTh: "แสวงหา", nameEn: "Sawaeng Ha", provinceCode: "15" },
  { code: "1506", nameTh: "วิเศษชัยชาญ", nameEn: "Wiset Chai Chan", provinceCode: "15" },
  { code: "1507", nameTh: "สามโก้", nameEn: "Samko", provinceCode: "15" },
  { code: "1601", nameTh: "เมืองลพบุรี", nameEn: "Mueang Lop Buri", provinceCode: "16" },
  { code: "1602", nameTh: "พัฒนานิคม", nameEn: "Phatthana Nikhom", provinceCode: "16" },
  { code: "1603", nameTh: "โคกสำโรง", nameEn: "Khok Samrong", provinceCode: "16" },
  { code: "1604", nameTh: "ชัยบาดาล", nameEn: "Chai Badan", provinceCode: "16" },
  { code: "1605", nameTh: "ท่าวุ้ง", nameEn: "Tha Wung", provinceCode: "16" },
  { code: "1606", nameTh: "บ้านหมี่", nameEn: "Ban Mi", provinceCode: "16" },
  { code: "1607", nameTh: "ท่าหลวง", nameEn: "Tha Luang", provinceCode: "16" },
  { code: "1608", nameTh: "สระโบสถ์", nameEn: "Sa Bot", provinceCode: "16" },
  { code: "1609", nameTh: "โคกเจริญ", nameEn: "Khok Charoen", provinceCode: "16" },
  { code: "1610", nameTh: "ลำสนธิ", nameEn: "Lam Sonthi", provinceCode: "16" },
  { code: "1611", nameTh: "หนองม่วง", nameEn: "Nong Muang", provinceCode: "16" },
  { code: "1701", nameTh: "เมืองสิงห์บุรี", nameEn: "Mueang Sing Buri", provinceCode: "17" },
  { code: "1702", nameTh: "บางระจัน", nameEn: "Bang Rachan", provinceCode: "17" },
  { code: "1703", nameTh: "ค่ายบางระจัน", nameEn: "Khai Bang Rachan", provinceCode: "17" },
  { code: "1704", nameTh: "พรหมบุรี", nameEn: "Phrom Buri", provinceCode: "17" },
  { code: "1705", nameTh: "ท่าช้าง", nameEn: "Tha Chang", provinceCode: "17" },
  { code: "1706", nameTh: "อินทร์บุรี", nameEn: "In Buri", provinceCode: "17" },
  { code: "1801", nameTh: "เมืองชัยนาท", nameEn: "Mueang Chai Nat", provinceCode: "18" },
  { code: "1802", nameTh: "มโนรมย์", nameEn: "Manorom", provinceCode: "18" },
  { code: "1803", nameTh: "วัดสิงห์", nameEn: "Wat Sing", provinceCode: "18" },
  { code: "1804", nameTh: "สรรพยา", nameEn: "Sapphaya", provinceCode: "18" },
  { code: "1805", nameTh: "สรรคบุรี", nameEn: "Sankhaburi", provinceCode: "18" },
  { code: "1806", nameTh: "หันคา", nameEn: "Hankha", provinceCode: "18" },
  { code: "1807", nameTh: "หนองมะโมง", nameEn: "Nong Mamong", provinceCode: "18" },
  { code: "1808", nameTh: "เนินขาม", nameEn: "Noen Kham", provinceCode: "18" },
  { code: "1901", nameTh: "เมืองสระบุรี", nameEn: "Mueang Saraburi", provinceCode: "19" },
  { code: "1902", nameTh: "แก่งคอย", nameEn: "Kaeng Khoi", provinceCode: "19" },
  { code: "1903", nameTh: "หนองแค", nameEn: "Nong Khae", provinceCode: "19" },
  { code: "1904", nameTh: "วิหารแดง", nameEn: "Wihan Daeng", provinceCode: "19" },
  { code: "1905", nameTh: "หนองแซง", nameEn: "Nong Saeng", provinceCode: "19" },
  { code: "1906", nameTh: "บ้านหมอ", nameEn: "Ban Mo", provinceCode: "19" },
  { code: "1907", nameTh: "ดอนพุด", nameEn: "Don Phut", provinceCode: "19" },
  { code: "1908", nameTh: "หนองโดน", nameEn: "Nong Don", provinceCode: "19" },
  { code: "1909", nameTh: "พระพุทธบาท", nameEn: "Phra Phutthabat", provinceCode: "19" },
  { code: "1910", nameTh: "เสาไห้", nameEn: "Sao Hai", provinceCode: "19" },
  { code: "1911", nameTh: "มวกเหล็ก", nameEn: "Muak Lek", provinceCode: "19" },
  { code: "1912", nameTh: "วังม่วง", nameEn: "Wang Muang", provinceCode: "19" },
  { code: "1913", nameTh: "เฉลิมพระเกียรติ", nameEn: "Chaloem Phra Kiat", provinceCode: "19" },
  { code: "2001", nameTh: "เมืองชลบุรี", nameEn: "Mueang Chon Buri", provinceCode: "20" },
  { code: "2002", nameTh: "บ้านบึง", nameEn: "Ban Bueng", provinceCode: "20" },
  { code: "2003", nameTh: "หนองใหญ่", nameEn: "Nong Yai", provinceCode: "20" },
  { code: "2004", nameTh: "บางละมุง", nameEn: "Bang Lamung", provinceCode: "20" },
  { code: "2005", nameTh: "พานทอง", nameEn: "Phan Thong", provinceCode: "20" },
  { code: "2006", nameTh: "พนัสนิคม", nameEn: "Phanat Nikhom", provinceCode: "20" },
  { code: "2007", nameTh: "ศรีราชา", nameEn: "Si Racha", provinceCode: "20" },
  { code: "2008", nameTh: "เกาะสีชัง", nameEn: "Ko Sichang", provinceCode: "20" },
  { code: "2009", nameTh: "สัตหีบ", nameEn: "Sattahip", provinceCode: "20" },
  { code: "2010", nameTh: "บ่อทอง", nameEn: "Bo Thong", provinceCode: "20" },
  { code: "2011", nameTh: "เกาะจันทร์", nameEn: "Ko Chan", provinceCode: "20" },
  { code: "2101", nameTh: "เมืองระยอง", nameEn: "Mueang Rayong", provinceCode: "21" },
  { code: "2102", nameTh: "บ้านฉาง", nameEn: "Ban Chang", provinceCode: "21" },
  { code: "2103", nameTh: "แกลง", nameEn: "Klaeng", provinceCode: "21" },
  { code: "2104", nameTh: "วังจันทร์", nameEn: "Wang Chan", provinceCode: "21" },
  { code: "2105", nameTh: "บ้านค่าย", nameEn: "Ban Khai", provinceCode: "21" },
  { code: "2106", nameTh: "ปลวกแดง", nameEn: "Pluak Daeng", provinceCode: "21" },
  { code: "2107", nameTh: "เขาชะเมา", nameEn: "Khao Chamao", provinceCode: "21" },
  { code: "2108", nameTh: "นิคมพัฒนา", nameEn: "Nikhom Phatthana", provinceCode: "21" },
  { code: "2201", nameTh: "เมืองจันทบุรี", nameEn: "Mueang Chanthaburi", provinceCode: "22" },
  { code: "2202", nameTh: "ขลุง", nameEn: "Khlung", provinceCode: "22" },
  { code: "2203", nameTh: "ท่าใหม่", nameEn: "Tha Mai", provinceCode: "22" },
  { code: "2204", nameTh: "โป่งน้ำร้อน", nameEn: "Pong Nam Ron", provinceCode: "22" },
  { code: "2205", nameTh: "มะขาม", nameEn: "Makham", provinceCode: "22" },
  { code: "2206", nameTh: "แหลมสิงห์", nameEn: "Laem Sing", provinceCode: "22" },
  { code: "2207", nameTh: "สอยดาว", nameEn: "Soi Dao", provinceCode: "22" },
  { code: "2208", nameTh: "แก่งหางแมว", nameEn: "Kaeng Hang Maeo", provinceCode: "22" },
  { code: "2209", nameTh: "นายายอาม", nameEn: "Na Yai Am", provinceCode: "22" },
  { code: "2210", nameTh: "เขาคิชฌกูฏ", nameEn: "Khao Khitchakut", provinceCode: "22" },
  { code: "2301", nameTh: "เมืองตราด", nameEn: "Mueang Trat", provinceCode: "23" },
  { code: "2302", nameTh: "คลองใหญ่", nameEn: "Khlong Yai", provinceCode: "23" },
  { code: "2303", nameTh: "เขาสมิง", nameEn: "Khao Saming", provinceCode: "23" },
  { code: "2304", nameTh: "บ่อไร่", nameEn: "Bo Rai", provinceCode: "23" },
  { code: "2305", nameTh: "แหลมงอบ", nameEn: "Laem Ngop", provinceCode: "23" },
  { code: "2306", nameTh: "เกาะกูด", nameEn: "Ko Kut", provinceCode: "23" },
  { code: "2307", nameTh: "เกาะช้าง", nameEn: "Ko Chang", provinceCode: "23" },
  { code: "2401", nameTh: "เมืองฉะเชิงเทรา", nameEn: "Mueang Chachoengsao", provinceCode: "24" },
  { code: "2402", nameTh: "บางคล้า", nameEn: "Bang Khla", provinceCode: "24" },
  { code: "2403", nameTh: "บางน้ำเปรี้ยว", nameEn: "Bang Nam Priao", provinceCode: "24" },
  { code: "2404", nameTh: "บางปะกง", nameEn: "Bang Pakong", provinceCode: "24" },
  { code: "2405", nameTh: "บ้านโพธิ์", nameEn: "Ban Pho", provinceCode: "24" },
  { code: "2406", nameTh: "พนมสารคาม", nameEn: "Phanom Sarakham", provinceCode: "24" },
  { code: "2407", nameTh: "ราชสาส์น", nameEn: "Ratchasan", provinceCode: "24" },
  { code: "2408", nameTh: "สนามชัยเขต", nameEn: "Sanam Chai Khet", provinceCode: "24" },
  { code: "2409", nameTh: "แปลงยาว", nameEn: "Plaeng Yao", provinceCode: "24" },
  { code: "2410", nameTh: "ท่าตะเกียบ", nameEn: "Tha Takiap", provinceCode: "24" },
  { code: "2411", nameTh: "คลองเขื่อน", nameEn: "Khlong Khuean", provinceCode: "24" },
  { code: "2501", nameTh: "เมืองปราจีนบุรี", nameEn: "Mueang Prachin Buri", provinceCode: "25" },
  { code: "2502", nameTh: "กบินทร์บุรี", nameEn: "Kabin Buri", provinceCode: "25" },
  { code: "2503", nameTh: "นาดี", nameEn: "Na Di", provinceCode: "25" },
  { code: "2506", nameTh: "บ้านสร้าง", nameEn: "Ban Sang", provinceCode: "25" },
  { code: "2507", nameTh: "ประจันตคาม", nameEn: "Prachantakham", provinceCode: "25" },
  { code: "2508", nameTh: "ศรีมหาโพธิ", nameEn: "Si Maha Phot", provinceCode: "25" },
  { code: "2509", nameTh: "ศรีมโหสถ", nameEn: "Si Mahosot", provinceCode: "25" },
  { code: "2601", nameTh: "เมืองนครนายก", nameEn: "Mueang Nakhon Nayok", provinceCode: "26" },
  { code: "2602", nameTh: "ปากพลี", nameEn: "Pak Phli", provinceCode: "26" },
  { code: "2603", nameTh: "บ้านนา", nameEn: "Ban Na", provinceCode: "26" },
  { code: "2604", nameTh: "องครักษ์", nameEn: "Ongkharak", provinceCode: "26" },
  { code: "2701", nameTh: "เมืองสระแก้ว", nameEn: "Mueang Sa Kaeo", provinceCode: "27" },
  { code: "2702", nameTh: "คลองหาด", nameEn: "Khlong Hat", provinceCode: "27" },
  { code: "2703", nameTh: "ตาพระยา", nameEn: "Ta Phraya", provinceCode: "27" },
  { code: "2704", nameTh: "วังน้ำเย็น", nameEn: "Wang Nam Yen", provinceCode: "27" },
  { code: "2705", nameTh: "วัฒนานคร", nameEn: "Watthana Nakhon", provinceCode: "27" },
  { code: "2706", nameTh: "อรัญประเทศ", nameEn: "Aranyaprathet", provinceCode: "27" },
  { code: "2707", nameTh: "เขาฉกรรจ์", nameEn: "Khao Chakan", provinceCode: "27" },
  { code: "2708", nameTh: "โคกสูง", nameEn: "Khok Sung", provinceCode: "27" },
  { code: "2709", nameTh: "วังสมบูรณ์", nameEn: "Wang Sombun", provinceCode: "27" },
  { code: "3001", nameTh: "เมืองนครราชสีมา", nameEn: "Mueang Nakhon Ratchasima", provinceCode: "30" },
  { code: "3002", nameTh: "ครบุรี", nameEn: "Khon Buri", provinceCode: "30" },
  { code: "3003", nameTh: "เสิงสาง", nameEn: "Soeng Sang", provinceCode: "30" },
  { code: "3004", nameTh: "คง", nameEn: "Khong", provinceCode: "30" },
  { code: "3005", nameTh: "บ้านเหลื่อม", nameEn: "Ban Lueam", provinceCode: "30" },
  { code: "3006", nameTh: "จักราช", nameEn: "Chakkarat", provinceCode: "30" },
  { code: "3007", nameTh: "โชคชัย", nameEn: "Chok Chai", provinceCode: "30" },
  { code: "3008", nameTh: "ด่านขุนทด", nameEn: "Dan Khun Thot", provinceCode: "30" },
  { code: "3009", nameTh: "โนนไทย", nameEn: "Non Thai", provinceCode: "30" },
  { code: "3010", nameTh: "โนนสูง", nameEn: "Non Sung", provinceCode: "30" },
  { code: "3011", nameTh: "ขามสะแกแสง", nameEn: "Kham Sakaesaeng", provinceCode: "30" },
  { code: "3012", nameTh: "บัวใหญ่", nameEn: "Bua Yai", provinceCode: "30" },
  { code: "3013", nameTh: "ประทาย", nameEn: "Prathai", provinceCode: "30" },
  { code: "3014", nameTh: "ปักธงชัย", nameEn: "Pak Thong Chai", provinceCode: "30" },
  { code: "3015", nameTh: "พิมาย", nameEn: "Phimai", provinceCode: "30" },
  { code: "3016", nameTh: "ห้วยแถลง", nameEn: "Huai Thalaeng", provinceCode: "30" },
  { code: "3017", nameTh: "ชุมพวง", nameEn: "Chum Phuang", provinceCode: "30" },
  { code: "3018", nameTh: "สูงเนิน", nameEn: "Sung Noen", provinceCode: "30" },
  { code: "3019", nameTh: "ขามทะเลสอ", nameEn: "Kham Thale So", provinceCode: "30" },
  { code: "3020", nameTh: "สีคิ้ว", nameEn: "Sikhio", provinceCode: "30" },
  { code: "3021", nameTh: "ปากช่อง", nameEn: "Pak Chong", provinceCode: "30" },
  { code: "3022", nameTh: "หนองบุญมาก", nameEn: "Nong Bun Mak", provinceCode: "30" },
  { code: "3023", nameTh: "แก้งสนามนาง", nameEn: "Kaeng Sanam Nang", provinceCode: "30" },
  { code: "3024", nameTh: "โนนแดง", nameEn: "Non Daeng", provinceCode: "30" },
  { code: "3025", nameTh: "วังน้ำเขียว", nameEn: "Wang Nam Khiao", provinceCode: "30" },
  { code: "3026", nameTh: "เทพารักษ์", nameEn: "Thepharak", provinceCode: "30" },
  { code: "3027", nameTh: "เมืองยาง", nameEn: "Mueang Yang", provinceCode: "30" },
  { code: "3028", nameTh: "พระทองคำ", nameEn: "Phra Thong Kham", provinceCode: "30" },
  { code: "3029", nameTh: "ลำทะเมนชัย", nameEn: "Lam Thamenchai", provinceCode: "30" },
  { code: "3030", nameTh: "บัวลาย", nameEn: "Bua Lai", provinceCode: "30" },
  { code: "3031", nameTh: "สีดา", nameEn: "Sida", provinceCode: "30" },
  { code: "3032", nameTh: "เฉลิมพระเกียรติ", nameEn: "Chaloem Phra Kiat", provinceCode: "30" },
  { code: "3101", nameTh: "เมืองบุรีรัมย์", nameEn: "Mueang Buri Ram", provinceCode: "31" },
  { code: "3102", nameTh: "คูเมือง", nameEn: "Khu Mueang", provinceCode: "31" },
  { code: "3103", nameTh: "กระสัง", nameEn: "Krasang", provinceCode: "31" },
  { code: "3104", nameTh: "นางรอง", nameEn: "Nang Rong", provinceCode: "31" },
  { code: "3105", nameTh: "หนองกี่", nameEn: "Nong Ki", provinceCode: "31" },
  { code: "3106", nameTh: "ละหานทราย", nameEn: "Lahan Sai", provinceCode: "31" },
  { code: "3107", nameTh: "ประโคนชัย", nameEn: "Prakhon Chai", provinceCode: "31" },
  { code: "3108", nameTh: "บ้านกรวด", nameEn: "Ban Kruat", provinceCode: "31" },
  { code: "3109", nameTh: "พุทไธสง", nameEn: "Phutthaisong", provinceCode: "31" },
  { code: "3110", nameTh: "ลำปลายมาศ", nameEn: "Lam Plai Mat", provinceCode: "31" },
  { code: "3111", nameTh: "สตึก", nameEn: "Satuek", provinceCode: "31" },
  { code: "3112", nameTh: "ปะคำ", nameEn: "Pakham", provinceCode: "31" },
  { code: "3113", nameTh: "นาโพธิ์", nameEn: "Na Pho", provinceCode: "31" },
  { code: "3114", nameTh: "หนองหงส์", nameEn: "Nong Hong", provinceCode: "31" },
  { code: "3115", nameTh: "พลับพลาชัย", nameEn: "Phlapphla Chai", provinceCode: "31" },
  { code: "3116", nameTh: "ห้วยราช", nameEn: "Huai Rat", provinceCode: "31" },
  { code: "3117", nameTh: "โนนสุวรรณ", nameEn: "Non Suwan", provinceCode: "31" },
  { code: "3118", nameTh: "ชำนิ", nameEn: "Chamni", provinceCode: "31" },
  { code: "3119", nameTh: "บ้านใหม่ไชยพจน์", nameEn: "Ban Mai Chaiyaphot", provinceCode: "31" },
  { code: "3120", nameTh: "โนนดินแดง", nameEn: "Non Din Daeng", provinceCode: "31" },
  { code: "3121", nameTh: "บ้านด่าน", nameEn: "Ban Dan", provinceCode: "31" },
  { code: "3122", nameTh: "แคนดง", nameEn: "Khaen Dong", provinceCode: "31" },
  { code: "3123", nameTh: "เฉลิมพระเกียรติ", nameEn: "Chaloem Phra Kiat", provinceCode: "31" },
  { code: "3201", nameTh: "เมืองสุรินทร์", nameEn: "Mueang Surin", provinceCode: "32" },
  { code: "3202", nameTh: "ชุมพลบุรี", nameEn: "Chumphon Buri", provinceCode: "32" },
  { code: "3203", nameTh: "ท่าตูม", nameEn: "Tha Tum", provinceCode: "32" },
  { code: "3204", nameTh: "จอมพระ", nameEn: "Chom Phra", provinceCode: "32" },
  { code: "3205", nameTh: "ปราสาท", nameEn: "Prasat", provinceCode: "32" },
  { code: "3206", nameTh: "กาบเชิง", nameEn: "Kap Choeng", provinceCode: "32" },
  { code: "3207", nameTh: "รัตนบุรี", nameEn: "Rattanaburi", provinceCode: "32" },
  { code: "3208", nameTh: "สนม", nameEn: "Sanom", provinceCode: "32" },
  { code: "3209", nameTh: "ศีขรภูมิ", nameEn: "Sikhoraphum", provinceCode: "32" },
  { code: "3210", nameTh: "สังขะ", nameEn: "Sangkha", provinceCode: "32" },
  { code: "3211", nameTh: "ลำดวน", nameEn: "Lamduan", provinceCode: "32" },
  { code: "3212", nameTh: "สำโรงทาบ", nameEn: "Samrong Thap", provinceCode: "32" },
  { code: "3213", nameTh: "บัวเชด", nameEn: "Buachet", provinceCode: "32" },
  { code: "3214", nameTh: "พนมดงรัก", nameEn: "Phanom Dong Rak", provinceCode: "32" },
  { code: "3215", nameTh: "ศรีณรงค์", nameEn: "Si Narong", provinceCode: "32" },
  { code: "3216", nameTh: "เขวาสินรินทร์", nameEn: "Khwao Sinarin", provinceCode: "32" },
  { code: "3217", nameTh: "โนนนารายณ์", nameEn: "Non Narai", provinceCode: "32" },
  { code: "3301", nameTh: "เมืองศรีสะเกษ", nameEn: "Mueang Si Sa Ket", provinceCode: "33" },
  { code: "3302", nameTh: "ยางชุมน้อย", nameEn: "Yang Chum Noi", provinceCode: "33" },
  { code: "3303", nameTh: "กันทรารมย์", nameEn: "Kanthararom", provinceCode: "33" },
  { code: "3304", nameTh: "กันทรลักษ์", nameEn: "Kantharalak", provinceCode: "33" },
  { code: "3305", nameTh: "ขุขันธ์", nameEn: "Khukhan", provinceCode: "33" },
  { code: "3306", nameTh: "ไพรบึง", nameEn: "Phrai Bueng", provinceCode: "33" },
  { code: "3307", nameTh: "ปรางค์กู่", nameEn: "Prang Ku", provinceCode: "33" },
  { code: "3308", nameTh: "ขุนหาญ", nameEn: "Khun Han", provinceCode: "33" },
  { code: "3309", nameTh: "ราษีไศล", nameEn: "Rasi Salai", provinceCode: "33" },
  { code: "3310", nameTh: "อุทุมพรพิสัย", nameEn: "Uthumphon Phisai", provinceCode: "33" },
  { code: "3311", nameTh: "บึงบูรพ์", nameEn: "Bueng Bun", provinceCode: "33" },
  { code: "3312", nameTh: "ห้วยทับทัน", nameEn: "Huai Thap Than", provinceCode: "33" },
  { code: "3313", nameTh: "โนนคูณ", nameEn: "Non Khun", provinceCode: "33" },
  { code: "3314", nameTh: "ศรีรัตนะ", nameEn: "Si Rattana", provinceCode: "33" },
  { code: "3315", nameTh: "น้ำเกลี้ยง", nameEn: "Nam Kliang", provinceCode: "33" },
  { code: "3316", nameTh: "วังหิน", nameEn: "Wang Hin", provinceCode: "33" },
  { code: "3317", nameTh: "ภูสิงห์", nameEn: "Phu Sing", provinceCode: "33" },
  { code: "3318", nameTh: "เมืองจันทร์", nameEn: "Mueang Chan", provinceCode: "33" },
  { code: "3319", nameTh: "เบญจลักษ์", nameEn: "Benchalak", provinceCode: "33" },
  { code: "3320", nameTh: "พยุห์", nameEn: "Phayu", provinceCode: "33" },
  { code: "3321", nameTh: "โพธิ์ศรีสุวรรณ", nameEn: "Pho Si Suwan", provinceCode: "33" },
  { code: "3322", nameTh: "ศิลาลาด", nameEn: "Sila Lat", provinceCode: "33" },
  { code: "3401", nameTh: "เมืองอุบลราชธานี", nameEn: "Mueang Ubon Ratchathani", provinceCode: "34" },
  { code: "3402", nameTh: "ศรีเมืองใหม่", nameEn: "Si Mueang Mai", provinceCode: "34" },
  { code: "3403", nameTh: "โขงเจียม", nameEn: "Khong Chiam", provinceCode: "34" },
  { code: "3404", nameTh: "เขื่องใน", nameEn: "Khueang Nai", provinceCode: "34" },
  { code: "3405", nameTh: "เขมราฐ", nameEn: "Khemarat", provinceCode: "34" },
  { code: "3407", nameTh: "เดชอุดม", nameEn: "Det Udom", provinceCode: "34" },
  { code: "3408", nameTh: "นาจะหลวย", nameEn: "Na Chaluai", provinceCode: "34" },
  { code: "3409", nameTh: "น้ำยืน", nameEn: "Nam Yuen", provinceCode: "34" },
  { code: "3410", nameTh: "บุณฑริก", nameEn: "Buntharik", provinceCode: "34" },
  { code: "3411", nameTh: "ตระการพืชผล", nameEn: "Trakan Phuet Phon", provinceCode: "34" },
  { code: "3412", nameTh: "กุดข้าวปุ้น", nameEn: "Kut Khaopun", provinceCode: "34" },
  { code: "3414", nameTh: "ม่วงสามสิบ", nameEn: "Muang Sam Sip", provinceCode: "34" },
  { code: "3415", nameTh: "วารินชำราบ", nameEn: "Warin Chamrap", provinceCode: "34" },
  { code: "3419", nameTh: "พิบูลมังสาหาร", nameEn: "Phibun Mangsahan", provinceCode: "34" },
  { code: "3420", nameTh: "ตาลสุม", nameEn: "Tan Sum", provinceCode: "34" },
  { code: "3421", nameTh: "โพธิ์ไทร", nameEn: "Pho Sai", provinceCode: "34" },
  { code: "3422", nameTh: "สำโรง", nameEn: "Samrong", provinceCode: "34" },
  { code: "3424", nameTh: "ดอนมดแดง", nameEn: "Don Mot Daeng", provinceCode: "34" },
  { code: "3425", nameTh: "สิรินธร", nameEn: "Sirindhorn", provinceCode: "34" },
  { code: "3426", nameTh: "ทุ่งศรีอุดม", nameEn: "Thung Si Udom", provinceCode: "34" },
  { code: "3429", nameTh: "นาเยีย", nameEn: "Na Yia", provinceCode: "34" },
  { code: "3430", nameTh: "นาตาล", nameEn: "Na Tan", provinceCode: "34" },
  { code: "3431", nameTh: "เหล่าเสือโก้ก", nameEn: "Lao Suea Kok", provinceCode: "34" },
  { code: "3432", nameTh: "สว่างวีระวงศ์", nameEn: "Sawang Wirawong", provinceCode: "34" },
  { code: "3433", nameTh: "น้ำขุ่น", nameEn: "Nam Khun", provinceCode: "34" },
  { code: "3501", nameTh: "เมืองยโสธร", nameEn: "Mueang Yasothon", provinceCode: "35" },
  { code: "3502", nameTh: "ทรายมูล", nameEn: "Sai Mun", provinceCode: "35" },
  { code: "3503", nameTh: "กุดชุม", nameEn: "Kut Chum", provinceCode: "35" },
  { code: "3504", nameTh: "คำเขื่อนแก้ว", nameEn: "Kham Khuean Kaeo", provinceCode: "35" },
  { code: "3505", nameTh: "ป่าติ้ว", nameEn: "Pa Tio", provinceCode: "35" },
  { code: "3506", nameTh: "มหาชนะชัย", nameEn: "Maha Chana Chai", provinceCode: "35" },
  { code: "3507", nameTh: "ค้อวัง", nameEn: "Kho Wang", provinceCode: "35" },
  { code: "3508", nameTh: "เลิงนกทา", nameEn: "Loeng Nok Tha", provinceCode: "35" },
  { code: "3509", nameTh: "ไทยเจริญ", nameEn: "Thai Charoen", provinceCode: "35" },
  { code: "3601", nameTh: "เมืองชัยภูมิ", nameEn: "Mueang Chaiyaphum", provinceCode: "36" },
  { code: "3602", nameTh: "บ้านเขว้า", nameEn: "Ban Khwao", provinceCode: "36" },
  { code: "3603", nameTh: "คอนสวรรค์", nameEn: "Khon Sawan", provinceCode: "36" },
  { code: "3604", nameTh: "เกษตรสมบูรณ์", nameEn: "Kaset Sombun", provinceCode: "36" },
  { code: "3605", nameTh: "หนองบัวแดง", nameEn: "Nong Bua Daeng", provinceCode: "36" },
  { code: "3606", nameTh: "จัตุรัส", nameEn: "Chatturat", provinceCode: "36" },
  { code: "3607", nameTh: "บำเหน็จณรงค์", nameEn: "Bamnet Narong", provinceCode: "36" },
  { code: "3608", nameTh: "หนองบัวระเหว", nameEn: "Nong Bua Rawe", provinceCode: "36" },
  { code: "3609", nameTh: "เทพสถิต", nameEn: "Thep Sathit", provinceCode: "36" },
  { code: "3610", nameTh: "ภูเขียว", nameEn: "Phu Khiao", provinceCode: "36" },
  { code: "3611", nameTh: "บ้านแท่น", nameEn: "Ban Thaen", provinceCode: "36" },
  { code: "3612", nameTh: "แก้งคร้อ", nameEn: "Kaeng Khro", provinceCode: "36" },
  { code: "3613", nameTh: "คอนสาร", nameEn: "Khon San", provinceCode: "36" },
  { code: "3614", nameTh: "ภักดีชุมพล", nameEn: "Phakdi Chumphon", provinceCode: "36" },
  { code: "3615", nameTh: "เนินสง่า", nameEn: "Noen Sa-nga", provinceCode: "36" },
  { code: "3616", nameTh: "ซับใหญ่", nameEn: "Sap Yai", provinceCode: "36" },
  { code: "3701", nameTh: "เมืองอำนาจเจริญ", nameEn: "Mueang Amnat Charoen", provinceCode: "37" },
  { code: "3702", nameTh: "ชานุมาน", nameEn: "Chanuman", provinceCode: "37" },
  { code: "3703", nameTh: "ปทุมราชวงศา", nameEn: "Pathum Ratchawongsa", provinceCode: "37" },
  { code: "3704", nameTh: "พนา", nameEn: "Phana", provinceCode: "37" },
  { code: "3705", nameTh: "เสนางคนิคม", nameEn: "Senangkhanikhom", provinceCode: "37" },
  { code: "3706", nameTh: "หัวตะพาน", nameEn: "Hua Taphan", provinceCode: "37" },
  { code: "3707", nameTh: "ลืออำนาจ", nameEn: "Lue Amnat", provinceCode: "37" },
  { code: "3801", nameTh: "เมืองบึงกาฬ", nameEn: "Mueang Bueng Kan", provinceCode: "38" },
  { code: "3802", nameTh: "เซกา", nameEn: "Seka", provinceCode: "38" },
  { code: "3803", nameTh: "โซ่พิสัย", nameEn: "So Phisai", provinceCode: "38" },
  { code: "3804", nameTh: "พรเจริญ", nameEn: "Phon Charoen", provinceCode: "38" },
  { code: "3805", nameTh: "ศรีวิไล", nameEn: "Si Wilai", provinceCode: "38" },
  { code: "3806", nameTh: "บึงโขงหลง", nameEn: "Bueng Khong Long", provinceCode: "38" },
  { code: "3807", nameTh: "ปากคาด", nameEn: "Pak Khat", provinceCode: "38" },
  { code: "3808", nameTh: "บุ่งคล้า", nameEn: "Bung Khla", provinceCode: "38" },
  { code: "3901", nameTh: "เมืองหนองบัวลำภู", nameEn: "Mueang Nong Bua Lam Phu", provinceCode: "39" },
  { code: "3902", nameTh: "นากลาง", nameEn: "Na Klang", provinceCode: "39" },
  { code: "3903", nameTh: "โนนสัง", nameEn: "Non Sang", provinceCode: "39" },
  { code: "3904", nameTh: "ศรีบุญเรือง", nameEn: "Si Bun Rueang", provinceCode: "39" },
  { code: "3905", nameTh: "สุวรรณคูหา", nameEn: "Suwannakhuha", provinceCode: "39" },
  { code: "3906", nameTh: "นาวัง", nameEn: "Na Wang", provinceCode: "39" },
  { code: "4001", nameTh: "เมืองขอนแก่น", nameEn: "Mueang Khon Kaen", provinceCode: "40" },
  { code: "4002", nameTh: "บ้านฝาง", nameEn: "Ban Fang", provinceCode: "40" },
  { code: "4003", nameTh: "พระยืน", nameEn: "Phra Yuen", provinceCode: "40" },
  { code: "4004", nameTh: "หนองเรือ", nameEn: "Nong Ruea", provinceCode: "40" },
  { code: "4005", nameTh: "ชุมแพ", nameEn: "Chum Phae", provinceCode: "40" },
  { code: "4006", nameTh: "สีชมพู", nameEn: "Si Chomphu", provinceCode: "40" },
  { code: "4007", nameTh: "น้ำพอง", nameEn: "Nam Phong", provinceCode: "40" },
  { code: "4008", nameTh: "อุบลรัตน์", nameEn: "Ubolratana", provinceCode: "40" },
  { code: "4009", nameTh: "กระนวน", nameEn: "Kranuan", provinceCode: "40" },
  { code: "4010", nameTh: "บ้านไผ่", nameEn: "Ban Phai", provinceCode: "40" },
  { code: "4011", nameTh: "เปือยน้อย", nameEn: "Pueai Noi", provinceCode: "40" },
  { code: "4012", nameTh: "พล", nameEn: "Phon", provinceCode: "40" },
  { code: "4013", nameTh: "แวงใหญ่", nameEn: "Waeng Yai", provinceCode: "40" },
  { code: "4014", nameTh: "แวงน้อย", nameEn: "Waeng Noi", provinceCode: "40" },
  { code: "4015", nameTh: "หนองสองห้อง", nameEn: "Nong Song Hong", provinceCode: "40" },
  { code: "4016", nameTh: "ภูเวียง", nameEn: "Phu Wiang", provinceCode: "40" },
  { code: "4017", nameTh: "มัญจาคีรี", nameEn: "Mancha Khiri", provinceCode: "40" },
  { code: "4018", nameTh: "ชนบท", nameEn: "Chonnabot", provinceCode: "40" },
  { code: "4019", nameTh: "เขาสวนกวาง", nameEn: "Khao Suan Kwang", provinceCode: "40" },
  { code: "4020", nameTh: "ภูผาม่าน", nameEn: "Phu Pha Man", provinceCode: "40" },
  { code: "4021", nameTh: "ซำสูง", nameEn: "Sam Sung", provinceCode: "40" },
  { code: "4022", nameTh: "โคกโพธิ์ไชย", nameEn: "Khok Pho Chai", provinceCode: "40" },
  { code: "4023", nameTh: "หนองนาคำ", nameEn: "Nong Na Kham", provinceCode: "40" },
  { code: "4024", nameTh: "บ้านแฮด", nameEn: "Ban Haet", provinceCode: "40" },
  { code: "4025", nameTh: "โนนศิลา", nameEn: "Non Sila", provinceCode: "40" },
  { code: "4029", nameTh: "เวียงเก่า", nameEn: "Wiang Kao", provinceCode: "40" },
  { code: "4101", nameTh: "เมืองอุดรธานี", nameEn: "Mueang Udon Thani", provinceCode: "41" },
  { code: "4102", nameTh: "กุดจับ", nameEn: "Kut Chap", provinceCode: "41" },
  { code: "4103", nameTh: "หนองวัวซอ", nameEn: "Nong Wua So", provinceCode: "41" },
  { code: "4104", nameTh: "กุมภวาปี", nameEn: "Kumphawapi", provinceCode: "41" },
  { code: "4105", nameTh: "โนนสะอาด", nameEn: "Non Sa-at", provinceCode: "41" },
  { code: "4106", nameTh: "หนองหาน", nameEn: "Nong Han", provinceCode: "41" },
  { code: "4107", nameTh: "ทุ่งฝน", nameEn: "Thung Fon", provinceCode: "41" },
  { code: "4108", nameTh: "ไชยวาน", nameEn: "Chai Wan", provinceCode: "41" },
  { code: "4109", nameTh: "ศรีธาตุ", nameEn: "Si That", provinceCode: "41" },
  { code: "4110", nameTh: "วังสามหมอ", nameEn: "Wang Sam Mo", provinceCode: "41" },
  { code: "4111", nameTh: "บ้านดุง", nameEn: "Ban Dung", provinceCode: "41" },
  { code: "4117", nameTh: "บ้านผือ", nameEn: "Ban Phue", provinceCode: "41" },
  { code: "4118", nameTh: "น้ำโสม", nameEn: "Nam Som", provinceCode: "41" },
  { code: "4119", nameTh: "เพ็ญ", nameEn: "Phen", provinceCode: "41" },
  { code: "4120", nameTh: "สร้างคอม", nameEn: "Sang Khom", provinceCode: "41" },
  { code: "4121", nameTh: "หนองแสง", nameEn: "Nong Saeng", provinceCode: "41" },
  { code: "4122", nameTh: "นายูง", nameEn: "Na Yung", provinceCode: "41" },
  { code: "4123", nameTh: "พิบูลย์รักษ์", nameEn: "Phibun Rak", provinceCode: "41" },
  { code: "4124", nameTh: "กู่แก้ว", nameEn: "Ku Kaeo", provinceCode: "41" },
  { code: "4125", nameTh: "ประจักษ์ศิลปาคม", nameEn: "Prachaksinlapakhom", provinceCode: "41" },
  { code: "4201", nameTh: "เมืองเลย", nameEn: "Mueang Loei", provinceCode: "42" },
  { code: "4202", nameTh: "นาด้วง", nameEn: "Na Duang", provinceCode: "42" },
  { code: "4203", nameTh: "เชียงคาน", nameEn: "Chiang Khan", provinceCode: "42" },
  { code: "4204", nameTh: "ปากชม", nameEn: "Pak Chom", provinceCode: "42" },
  { code: "4205", nameTh: "ด่านซ้าย", nameEn: "Dan Sai", provinceCode: "42" },
  { code: "4206", nameTh: "นาแห้ว", nameEn: "Na Haeo", provinceCode: "42" },
  { code: "4207", nameTh: "ภูเรือ", nameEn: "Phu Ruea", provinceCode: "42" },
  { code: "4208", nameTh: "ท่าลี่", nameEn: "Tha Li", provinceCode: "42" },
  { code: "4209", nameTh: "วังสะพุง", nameEn: "Wang Saphung", provinceCode: "42" },
  { code: "4210", nameTh: "ภูกระดึง", nameEn: "Phu Kradueng", provinceCode: "42" },
  { code: "4211", nameTh: "ภูหลวง", nameEn: "Phu Luang", provinceCode: "42" },
  { code: "4212", nameTh: "ผาขาว", nameEn: "Pha Khao", provinceCode: "42" },
  { code: "4213", nameTh: "เอราวัณ", nameEn: "Erawan", provinceCode: "42" },
  { code: "4214", nameTh: "หนองหิน", nameEn: "Nong Hin", provinceCode: "42" },
  { code: "4301", nameTh: "เมืองหนองคาย", nameEn: "Mueang Nong Khai", provinceCode: "43" },
  { code: "4302", nameTh: "ท่าบ่อ", nameEn: "Tha Bo", provinceCode: "43" },
  { code: "4305", nameTh: "โพนพิสัย", nameEn: "Phon Phisai", provinceCode: "43" },
  { code: "4307", nameTh: "ศรีเชียงใหม่", nameEn: "Si Chiang Mai", provinceCode: "43" },
  { code: "4308", nameTh: "สังคม", nameEn: "Sangkhom", provinceCode: "43" },
  { code: "4314", nameTh: "สระใคร", nameEn: "Sakhrai", provinceCode: "43" },
  { code: "4315", nameTh: "เฝ้าไร่", nameEn: "Fao Rai", provinceCode: "43" },
  { code: "4316", nameTh: "รัตนวาปี", nameEn: "Rattanawapi", provinceCode: "43" },
  { code: "4317", nameTh: "โพธิ์ตาก", nameEn: "Pho Tak", provinceCode: "43" },
  { code: "4401", nameTh: "เมืองมหาสารคาม", nameEn: "Mueang Maha Sarakham", provinceCode: "44" },
  { code: "4402", nameTh: "แกดำ", nameEn: "Kae Dam", provinceCode: "44" },
  { code: "4403", nameTh: "โกสุมพิสัย", nameEn: "Kosum Phisai", provinceCode: "44" },
  { code: "4404", nameTh: "กันทรวิชัย", nameEn: "Kantharawichai", provinceCode: "44" },
  { code: "4405", nameTh: "เชียงยืน", nameEn: "Chiang Yuen", provinceCode: "44" },
  { code: "4406", nameTh: "บรบือ", nameEn: "Borabue", provinceCode: "44" },
  { code: "4407", nameTh: "นาเชือก", nameEn: "Na Chueak", provinceCode: "44" },
  { code: "4408", nameTh: "พยัคฆภูมิพิสัย", nameEn: "Phayakkhaphum Phisai", provinceCode: "44" },
  { code: "4409", nameTh: "วาปีปทุม", nameEn: "Wapi Pathum", provinceCode: "44" },
  { code: "4410", nameTh: "นาดูน", nameEn: "Na Dun", provinceCode: "44" },
  { code: "4411", nameTh: "ยางสีสุราช", nameEn: "Yang Sisurat", provinceCode: "44" },
  { code: "4412", nameTh: "กุดรัง", nameEn: "Kut Rang", provinceCode: "44" },
  { code: "4413", nameTh: "ชื่นชม", nameEn: "Chuen Chom", provinceCode: "44" },
  { code: "4501", nameTh: "เมืองร้อยเอ็ด", nameEn: "Mueang Roi Et", provinceCode: "45" },
  { code: "4502", nameTh: "เกษตรวิสัย", nameEn: "Kaset Wisai", provinceCode: "45" },
  { code: "4503", nameTh: "ปทุมรัตต์", nameEn: "Pathum Rat", provinceCode: "45" },
  { code: "4504", nameTh: "จตุรพักตรพิมาน", nameEn: "Chaturaphak Phiman", provinceCode: "45" },
  { code: "4505", nameTh: "ธวัชบุรี", nameEn: "Thawat Buri", provinceCode: "45" },
  { code: "4506", nameTh: "พนมไพร", nameEn: "Phanom Phrai", provinceCode: "45" },
  { code: "4507", nameTh: "โพนทอง", nameEn: "Phon Thong", provinceCode: "45" },
  { code: "4508", nameTh: "โพธิ์ชัย", nameEn: "Pho Chai", provinceCode: "45" },
  { code: "4509", nameTh: "หนองพอก", nameEn: "Nong Phok", provinceCode: "45" },
  { code: "4510", nameTh: "เสลภูมิ", nameEn: "Selaphum", provinceCode: "45" },
  { code: "4511", nameTh: "สุวรรณภูมิ", nameEn: "Suwannaphum", provinceCode: "45" },
  { code: "4512", nameTh: "เมืองสรวง", nameEn: "Mueang Suang", provinceCode: "45" },
  { code: "4513", nameTh: "โพนทราย", nameEn: "Phon Sai", provinceCode: "45" },
  { code: "4514", nameTh: "อาจสามารถ", nameEn: "At Samat", provinceCode: "45" },
  { code: "4515", nameTh: "เมยวดี", nameEn: "Moei Wadi", provinceCode: "45" },
  { code: "4516", nameTh: "ศรีสมเด็จ", nameEn: "Si Somdet", provinceCode: "45" },
  { code: "4517", nameTh: "จังหาร", nameEn: "Changhan", provinceCode: "45" },
  { code: "4518", nameTh: "เชียงขวัญ", nameEn: "Chiang Khwan", provinceCode: "45" },
  { code: "4519", nameTh: "หนองฮี", nameEn: "Nong Hi", provinceCode: "45" },
  { code: "4520", nameTh: "ทุ่งเขาหลวง", nameEn: "Thung Khao Luang", provinceCode: "45" },
  { code: "4601", nameTh: "เมืองกาฬสินธุ์", nameEn: "Mueang Kalasin", provinceCode: "46" },
  { code: "4602", nameTh: "นามน", nameEn: "Na Mon", provinceCode: "46" },
  { code: "4603", nameTh: "กมลาไสย", nameEn: "Kamalasai", provinceCode: "46" },
  { code: "4604", nameTh: "ร่องคำ", nameEn: "Rong Kham", provinceCode: "46" },
  { code: "4605", nameTh: "กุฉินารายณ์", nameEn: "Kuchinarai", provinceCode: "46" },
  { code: "4606", nameTh: "เขาวง", nameEn: "Khao Wong", provinceCode: "46" },
  { code: "4607", nameTh: "ยางตลาด", nameEn: "Yang Talat", provinceCode: "46" },
  { code: "4608", nameTh: "ห้วยเม็ก", nameEn: "Huai Mek", provinceCode: "46" },
  { code: "4609", nameTh: "สหัสขันธ์", nameEn: "Sahatsakhan", provinceCode: "46" },
  { code: "4610", nameTh: "คำม่วง", nameEn: "Kham Muang", provinceCode: "46" },
  { code: "4611", nameTh: "ท่าคันโท", nameEn: "Tha Khantho", provinceCode: "46" },
  { code: "4612", nameTh: "หนองกุงศรี", nameEn: "Nong Kung Si", provinceCode: "46" },
  { code: "4613", nameTh: "สมเด็จ", nameEn: "Somdet", provinceCode: "46" },
  { code: "4614", nameTh: "ห้วยผึ้ง", nameEn: "Huai Phueng", provinceCode: "46" },
  { code: "4615", nameTh: "สามชัย", nameEn: "Sam Chai", provinceCode: "46" },
  { code: "4616", nameTh: "นาคู", nameEn: "Na Khu", provinceCode: "46" },
  { code: "4617", nameTh: "ดอนจาน", nameEn: "Don Chan", provinceCode: "46" },
  { code: "4618", nameTh: "ฆ้องชัย", nameEn: "Khong Chai", provinceCode: "46" },
  { code: "4701", nameTh: "เมืองสกลนคร", nameEn: "Mueang Sakon Nakhon", provinceCode: "47" },
  { code: "4702", nameTh: "กุสุมาลย์", nameEn: "Kusuman", provinceCode: "47" },
  { code: "4703", nameTh: "กุดบาก", nameEn: "Kut Bak", provinceCode: "47" },
  { code: "4704", nameTh: "พรรณานิคม", nameEn: "Phanna Nikhom", provinceCode: "47" },
  { code: "4705", nameTh: "พังโคน", nameEn: "Phang Khon", provinceCode: "47" },
  { code: "4706", nameTh: "วาริชภูมิ", nameEn: "Waritchaphum", provinceCode: "47" },
  { code: "4707", nameTh: "นิคมน้ำอูน", nameEn: "Nikhom Nam Un", provinceCode: "47" },
  { code: "4708", nameTh: "วานรนิวาส", nameEn: "Wanon Niwat", provinceCode: "47" },
  { code: "4709", nameTh: "คำตากล้า", nameEn: "Kham Ta Kla", provinceCode: "47" },
  { code: "4710", nameTh: "บ้านม่วง", nameEn: "Ban Muang", provinceCode: "47" },
  { code: "4711", nameTh: "อากาศอำนวย", nameEn: "Akat Amnuai", provinceCode: "47" },
  { code: "4712", nameTh: "สว่างแดนดิน", nameEn: "Sawang Daen Din", provinceCode: "47" },
  { code: "4713", nameTh: "ส่องดาว", nameEn: "Song Dao", provinceCode: "47" },
  { code: "4714", nameTh: "เต่างอย", nameEn: "Tao Ngoi", provinceCode: "47" },
  { code: "4715", nameTh: "โคกศรีสุพรรณ", nameEn: "Khok Si Suphan", provinceCode: "47" },
  { code: "4716", nameTh: "เจริญศิลป์", nameEn: "Charoen Sin", provinceCode: "47" },
  { code: "4717", nameTh: "โพนนาแก้ว", nameEn: "Phon Na Kaeo", provinceCode: "47" },
  { code: "4718", nameTh: "ภูพาน", nameEn: "Phu Phan", provinceCode: "47" },
  { code: "4801", nameTh: "เมืองนครพนม", nameEn: "Mueang Nakhon Phanom", provinceCode: "48" },
  { code: "4802", nameTh: "ปลาปาก", nameEn: "Pla Pak", provinceCode: "48" },
  { code: "4803", nameTh: "ท่าอุเทน", nameEn: "Tha Uthen", provinceCode: "48" },
  { code: "4804", nameTh: "บ้านแพง", nameEn: "Ban Phaeng", provinceCode: "48" },
  { code: "4805", nameTh: "ธาตุพนม", nameEn: "That Phanom", provinceCode: "48" },
  { code: "4806", nameTh: "เรณูนคร", nameEn: "Renu Nakhon", provinceCode: "48" },
  { code: "4807", nameTh: "นาแก", nameEn: "Na Kae", provinceCode: "48" },
  { code: "4808", nameTh: "ศรีสงคราม", nameEn: "Si Songkhram", provinceCode: "48" },
  { code: "4809", nameTh: "นาหว้า", nameEn: "Na Wa", provinceCode: "48" },
  { code: "4810", nameTh: "โพนสวรรค์", nameEn: "Phon Sawan", provinceCode: "48" },
  { code: "4811", nameTh: "นาทม", nameEn: "Na Thom", provinceCode: "48" },
  { code: "4812", nameTh: "วังยาง", nameEn: "Wang Yang", provinceCode: "48" },
  { code: "4901", nameTh: "เมืองมุกดาหาร", nameEn: "Mueang Mukdahan", provinceCode: "49" },
  { code: "4902", nameTh: "นิคมคำสร้อย", nameEn: "Nikhom Kham Soi", provinceCode: "49" },
  { code: "4903", nameTh: "ดอนตาล", nameEn: "Don Tan", provinceCode: "49" },
  { code: "4904", nameTh: "ดงหลวง", nameEn: "Dong Luang", provinceCode: "49" },
  { code: "4905", nameTh: "คำชะอี", nameEn: "Khamcha-i", provinceCode: "49" },
  { code: "4906", nameTh: "หว้านใหญ่", nameEn: "Wan Yai", provinceCode: "49" },
  { code: "4907", nameTh: "หนองสูง", nameEn: "Nong Sung", provinceCode: "49" },
  { code: "5001", nameTh: "เมืองเชียงใหม่", nameEn: "Mueang Chiang Mai", provinceCode: "50" },
  { code: "5002", nameTh: "จอมทอง", nameEn: "Chom Thong", provinceCode: "50" },
  { code: "5003", nameTh: "แม่แจ่ม", nameEn: "Mae Chaem", provinceCode: "50" },
  { code: "5004", nameTh: "เชียงดาว", nameEn: "Chiang Dao", provinceCode: "50" },
  { code: "5005", nameTh: "ดอยสะเก็ด", nameEn: "Doi Saket", provinceCode: "50" },
  { code: "5006", nameTh: "แม่แตง", nameEn: "Mae Taeng", provinceCode: "50" },
  { code: "5007", nameTh: "แม่ริม", nameEn: "Mae Rim", provinceCode: "50" },
  { code: "5008", nameTh: "สะเมิง", nameEn: "Samoeng", provinceCode: "50" },
  { code: "5009", nameTh: "ฝาง", nameEn: "Fang", provinceCode: "50" },
  { code: "5010", nameTh: "แม่อาย", nameEn: "Mae Ai", provinceCode: "50" },
  { code: "5011", nameTh: "พร้าว", nameEn: "Phrao", provinceCode: "50" },
  { code: "5012", nameTh: "สันป่าตอง", nameEn: "San Pa Tong", provinceCode: "50" },
  { code: "5013", nameTh: "สันกำแพง", nameEn: "San Kamphaeng", provinceCode: "50" },
  { code: "5014", nameTh: "สันทราย", nameEn: "San Sai", provinceCode: "50" },
  { code: "5015", nameTh: "หางดง", nameEn: "Hang Dong", provinceCode: "50" },
  { code: "5016", nameTh: "ฮอด", nameEn: "Hot", provinceCode: "50" },
  { code: "5017", nameTh: "ดอยเต่า", nameEn: "Doi Tao", provinceCode: "50" },
  { code: "5018", nameTh: "อมก๋อย", nameEn: "Omkoi", provinceCode: "50" },
  { code: "5019", nameTh: "สารภี", nameEn: "Saraphi", provinceCode: "50" },
  { code: "5020", nameTh: "เวียงแหง", nameEn: "Wiang Haeng", provinceCode: "50" },
  { code: "5021", nameTh: "ไชยปราการ", nameEn: "Chai Prakan", provinceCode: "50" },
  { code: "5022", nameTh: "แม่วาง", nameEn: "Mae Wang", provinceCode: "50" },
  { code: "5023", nameTh: "แม่ออน", nameEn: "Mae On", provinceCode: "50" },
  { code: "5024", nameTh: "ดอยหล่อ", nameEn: "Doi Lo", provinceCode: "50" },
  { code: "5025", nameTh: "กัลยาณิวัฒนา", nameEn: "Galyani Vadhana", provinceCode: "50" },
  { code: "5101", nameTh: "เมืองลำพูน", nameEn: "Mueang Lamphun", provinceCode: "51" },
  { code: "5102", nameTh: "แม่ทา", nameEn: "Mae Tha", provinceCode: "51" },
  { code: "5103", nameTh: "บ้านโฮ่ง", nameEn: "Ban Hong", provinceCode: "51" },
  { code: "5104", nameTh: "ลี้", nameEn: "Li", provinceCode: "51" },
  { code: "5105", nameTh: "ทุ่งหัวช้าง", nameEn: "Thung Hua Chang", provinceCode: "51" },
  { code: "5106", nameTh: "ป่าซาง", nameEn: "Pa Sang", provinceCode: "51" },
  { code: "5107", nameTh: "บ้านธิ", nameEn: "Ban Thi", provinceCode: "51" },
  { code: "5108", nameTh: "เวียงหนองล่อง", nameEn: "Wiang Nong Long", provinceCode: "51" },
  { code: "5201", nameTh: "เมืองลำปาง", nameEn: "Mueang Lampang", provinceCode: "52" },
  { code: "5202", nameTh: "แม่เมาะ", nameEn: "Mae Mo", provinceCode: "52" },
  { code: "5203", nameTh: "เกาะคา", nameEn: "Ko Kha", provinceCode: "52" },
  { code: "5204", nameTh: "เสริมงาม", nameEn: "Soem Ngam", provinceCode: "52" },
  { code: "5205", nameTh: "งาว", nameEn: "Ngao", provinceCode: "52" },
  { code: "5206", nameTh: "แจ้ห่ม", nameEn: "Chae Hom", provinceCode: "52" },
  { code: "5207", nameTh: "วังเหนือ", nameEn: "Wang Nuea", provinceCode: "52" },
  { code: "5208", nameTh: "เถิน", nameEn: "Thoen", provinceCode: "52" },
  { code: "5209", nameTh: "แม่พริก", nameEn: "Mae Phrik", provinceCode: "52" },
  { code: "5210", nameTh: "แม่ทะ", nameEn: "Mae Tha", provinceCode: "52" },
  { code: "5211", nameTh: "สบปราบ", nameEn: "Sop Prap", provinceCode: "52" },
  { code: "5212", nameTh: "ห้างฉัตร", nameEn: "Hang Chat", provinceCode: "52" },
  { code: "5213", nameTh: "เมืองปาน", nameEn: "Mueang Pan", provinceCode: "52" },
  { code: "5301", nameTh: "เมืองอุตรดิตถ์", nameEn: "Mueang Uttaradit", provinceCode: "53" },
  { code: "5302", nameTh: "ตรอน", nameEn: "Tron", provinceCode: "53" },
  { code: "5303", nameTh: "ท่าปลา", nameEn: "Tha Pla", provinceCode: "53" },
  { code: "5304", nameTh: "น้ำปาด", nameEn: "Nam Pat", provinceCode: "53" },
  { code: "5305", nameTh: "ฟากท่า", nameEn: "Fak Tha", provinceCode: "53" },
  { code: "5306", nameTh: "บ้านโคก", nameEn: "Ban Khok", provinceCode: "53" },
  { code: "5307", nameTh: "พิชัย", nameEn: "Phichai", provinceCode: "53" },
  { code: "5308", nameTh: "ลับแล", nameEn: "Laplae", provinceCode: "53" },
  { code: "5309", nameTh: "ทองแสนขัน", nameEn: "Thong Saen Khan", provinceCode: "53" },
  { code: "5401", nameTh: "เมืองแพร่", nameEn: "Mueang Phrae", provinceCode: "54" },
  { code: "5402", nameTh: "ร้องกวาง", nameEn: "Rong Kwang", provinceCode: "54" },
  { code: "5403", nameTh: "ลอง", nameEn: "Long", provinceCode: "54" },
  { code: "5404", nameTh: "สูงเม่น", nameEn: "Sung Men", provinceCode: "54" },
  { code: "5405", nameTh: "เด่นชัย", nameEn: "Den Chai", provinceCode: "54" },
  { code: "5406", nameTh: "สอง", nameEn: "Song", provinceCode: "54" },
  { code: "5407", nameTh: "วังชิ้น", nameEn: "Wang Chin", provinceCode: "54" },
  { code: "5408", nameTh: "หนองม่วงไข่", nameEn: "Nong Muang Khai", provinceCode: "54" },
  { code: "5501", nameTh: "เมืองน่าน", nameEn: "Mueang Nan", provinceCode: "55" },
  { code: "5502", nameTh: "แม่จริม", nameEn: "Mae Charim", provinceCode: "55" },
  { code: "5503", nameTh: "บ้านหลวง", nameEn: "Ban Luang", provinceCode: "55" },
  { code: "5504", nameTh: "นาน้อย", nameEn: "Na Noi", provinceCode: "55" },
  { code: "5505", nameTh: "ปัว", nameEn: "Pua", provinceCode: "55" },
  { code: "5506", nameTh: "ท่าวังผา", nameEn: "Tha Wang Pha", provinceCode: "55" },
  { code: "5507", nameTh: "เวียงสา", nameEn: "Wiang Sa", provinceCode: "55" },
  { code: "5508", nameTh: "ทุ่งช้าง", nameEn: "Thung Chang", provinceCode: "55" },
  { code: "5509", nameTh: "เชียงกลาง", nameEn: "Chiang Klang", provinceCode: "55" },
  { code: "5510", nameTh: "นาหมื่น", nameEn: "Na Muen", provinceCode: "55" },
  { code: "5511", nameTh: "สันติสุข", nameEn: "Santi Suk", provinceCode: "55" },
  { code: "5512", nameTh: "บ่อเกลือ", nameEn: "Bo Kluea", provinceCode: "55" },
  { code: "5513", nameTh: "สองแคว", nameEn: "Song Khwae", provinceCode: "55" },
  { code: "5514", nameTh: "ภูเพียง", nameEn: "Phu Phiang", provinceCode: "55" },
  { code: "5515", nameTh: "เฉลิมพระเกียรติ", nameEn: "Chaloem Phra Kiat", provinceCode: "55" },
  { code: "5601", nameTh: "เมืองพะเยา", nameEn: "Mueang Phayao", provinceCode: "56" },
  { code: "5602", nameTh: "จุน", nameEn: "Chun", provinceCode: "56" },
  { code: "5603", nameTh: "เชียงคำ", nameEn: "Chiang Kham", provinceCode: "56" },
  { code: "5604", nameTh: "เชียงม่วน", nameEn: "Chiang Muan", provinceCode: "56" },
  { code: "5605", nameTh: "ดอกคำใต้", nameEn: "Dok Khamtai", provinceCode: "56" },
  { code: "5606", nameTh: "ปง", nameEn: "Pong", provinceCode: "56" },
  { code: "5607", nameTh: "แม่ใจ", nameEn: "Mae Chai", provinceCode: "56" },
  { code: "5608", nameTh: "ภูซาง", nameEn: "Phu Sang", provinceCode: "56" },
  { code: "5609", nameTh: "ภูกามยาว", nameEn: "Phu Kamyao", provinceCode: "56" },
  { code: "5701", nameTh: "เมืองเชียงราย", nameEn: "Mueang Chiang Rai", provinceCode: "57" },
  { code: "5702", nameTh: "เวียงชัย", nameEn: "Wiang Chai", provinceCode: "57" },
  { code: "5703", nameTh: "เชียงของ", nameEn: "Chiang Khong", provinceCode: "57" },
  { code: "5704", nameTh: "เทิง", nameEn: "Thoeng", provinceCode: "57" },
  { code: "5705", nameTh: "พาน", nameEn: "Phan", provinceCode: "57" },
  { code: "5706", nameTh: "ป่าแดด", nameEn: "Pa Daet", provinceCode: "57" },
  { code: "5707", nameTh: "แม่จัน", nameEn: "Mae Chan", provinceCode: "57" },
  { code: "5708", nameTh: "เชียงแสน", nameEn: "Chiang Saen", provinceCode: "57" },
  { code: "5709", nameTh: "แม่สาย", nameEn: "Mae Sai", provinceCode: "57" },
  { code: "5710", nameTh: "แม่สรวย", nameEn: "Mae Suai", provinceCode: "57" },
  { code: "5711", nameTh: "เวียงป่าเป้า", nameEn: "Wiang Pa Pao", provinceCode: "57" },
  { code: "5712", nameTh: "พญาเม็งราย", nameEn: "Phaya Mengrai", provinceCode: "57" },
  { code: "5713", nameTh: "เวียงแก่น", nameEn: "Wiang Kaen", provinceCode: "57" },
  { code: "5714", nameTh: "ขุนตาล", nameEn: "Khun Tan", provinceCode: "57" },
  { code: "5715", nameTh: "แม่ฟ้าหลวง", nameEn: "Mae Fa Luang", provinceCode: "57" },
  { code: "5716", nameTh: "แม่ลาว", nameEn: "Mae Lao", provinceCode: "57" },
  { code: "5717", nameTh: "เวียงเชียงรุ้ง", nameEn: "Wiang Chiang Rung", provinceCode: "57" },
  { code: "5718", nameTh: "ดอยหลวง", nameEn: "Doi Luang", provinceCode: "57" },
  { code: "5801", nameTh: "เมืองแม่ฮ่องสอน", nameEn: "Mueang Mae Hong Son", provinceCode: "58" },
  { code: "5802", nameTh: "ขุนยวม", nameEn: "Khun Yuam", provinceCode: "58" },
  { code: "5803", nameTh: "ปาย", nameEn: "Pai", provinceCode: "58" },
  { code: "5804", nameTh: "แม่สะเรียง", nameEn: "Mae Sariang", provinceCode: "58" },
  { code: "5805", nameTh: "แม่ลาน้อย", nameEn: "Mae La Noi", provinceCode: "58" },
  { code: "5806", nameTh: "สบเมย", nameEn: "Sop Moei", provinceCode: "58" },
  { code: "5807", nameTh: "ปางมะผ้า", nameEn: "Pang Mapha", provinceCode: "58" },
  { code: "6001", nameTh: "เมืองนครสวรรค์", nameEn: "Mueang Nakhon Sawan", provinceCode: "60" },
  { code: "6002", nameTh: "โกรกพระ", nameEn: "Krok Phra", provinceCode: "60" },
  { code: "6003", nameTh: "ชุมแสง", nameEn: "Chum Saeng", provinceCode: "60" },
  { code: "6004", nameTh: "หนองบัว", nameEn: "Nong Bua", provinceCode: "60" },
  { code: "6005", nameTh: "บรรพตพิสัย", nameEn: "Banphot Phisai", provinceCode: "60" },
  { code: "6006", nameTh: "เก้าเลี้ยว", nameEn: "Kao Liao", provinceCode: "60" },
  { code: "6007", nameTh: "ตาคลี", nameEn: "Takhli", provinceCode: "60" },
  { code: "6008", nameTh: "ท่าตะโก", nameEn: "Takhli", provinceCode: "60" },
  { code: "6009", nameTh: "ไพศาลี", nameEn: "Phaisali", provinceCode: "60" },
  { code: "6010", nameTh: "พยุหะคีรี", nameEn: "Phayuha Khiri", provinceCode: "60" },
  { code: "6011", nameTh: "ลาดยาว", nameEn: "Phayuha Khiri", provinceCode: "60" },
  { code: "6012", nameTh: "ตากฟ้า", nameEn: "Tak Fa", provinceCode: "60" },
  { code: "6013", nameTh: "แม่วงก์", nameEn: "Mae Wong", provinceCode: "60" },
  { code: "6014", nameTh: "แม่เปิน", nameEn: "Mae Poen", provinceCode: "60" },
  { code: "6015", nameTh: "ชุมตาบง", nameEn: "Chum Ta Bong", provinceCode: "60" },
  { code: "6101", nameTh: "เมืองอุทัยธานี", nameEn: "Mueang Uthai Thani", provinceCode: "61" },
  { code: "6102", nameTh: "ทัพทัน", nameEn: "Thap Than", provinceCode: "61" },
  { code: "6103", nameTh: "สว่างอารมณ์", nameEn: "Sawang Arom", provinceCode: "61" },
  { code: "6104", nameTh: "หนองฉาง", nameEn: "Nong Chang", provinceCode: "61" },
  { code: "6105", nameTh: "หนองขาหย่าง", nameEn: "Nong Khayang", provinceCode: "61" },
  { code: "6106", nameTh: "บ้านไร่", nameEn: "Ban Rai", provinceCode: "61" },
  { code: "6107", nameTh: "ลานสัก", nameEn: "Lan Sak", provinceCode: "61" },
  { code: "6108", nameTh: "ห้วยคต", nameEn: "Huai Khot", provinceCode: "61" },
  { code: "6201", nameTh: "เมืองกำแพงเพชร", nameEn: "Mueang Kamphaeng Phet", provinceCode: "62" },
  { code: "6202", nameTh: "ไทรงาม", nameEn: "Sai Ngam", provinceCode: "62" },
  { code: "6203", nameTh: "คลองลาน", nameEn: "Khlong Lan", provinceCode: "62" },
  { code: "6204", nameTh: "ขาณุวรลักษบุรี", nameEn: "Khanu Woralaksaburi", provinceCode: "62" },
  { code: "6205", nameTh: "คลองขลุง", nameEn: "Khlong Khlung", provinceCode: "62" },
  { code: "6206", nameTh: "พรานกระต่าย", nameEn: "Phran Kratai", provinceCode: "62" },
  { code: "6207", nameTh: "ลานกระบือ", nameEn: "Lan Krabue", provinceCode: "62" },
  { code: "6208", nameTh: "ทรายทองวัฒนา", nameEn: "Sai Thong Watthana", provinceCode: "62" },
  { code: "6209", nameTh: "ปางศิลาทอง", nameEn: "Pang Sila Thong", provinceCode: "62" },
  { code: "6210", nameTh: "บึงสามัคคี", nameEn: "Bueng Samakkhi", provinceCode: "62" },
  { code: "6211", nameTh: "โกสัมพีนคร", nameEn: "Kosamphi Nakhon", provinceCode: "62" },
  { code: "6301", nameTh: "เมืองตาก", nameEn: "Mueang Tak", provinceCode: "63" },
  { code: "6302", nameTh: "บ้านตาก", nameEn: "Ban Tak", provinceCode: "63" },
  { code: "6303", nameTh: "สามเงา", nameEn: "Sam Ngao", provinceCode: "63" },
  { code: "6304", nameTh: "แม่ระมาด", nameEn: "Mae Ramat", provinceCode: "63" },
  { code: "6305", nameTh: "ท่าสองยาง", nameEn: "Tha Song Yang", provinceCode: "63" },
  { code: "6306", nameTh: "แม่สอด", nameEn: "Mae Sot", provinceCode: "63" },
  { code: "6307", nameTh: "พบพระ", nameEn: "Phop Phra", provinceCode: "63" },
  { code: "6308", nameTh: "อุ้มผาง", nameEn: "Umphang", provinceCode: "63" },
  { code: "6309", nameTh: "วังเจ้า", nameEn: "Wang Chao", provinceCode: "63" },
  { code: "6401", nameTh: "เมืองสุโขทัย", nameEn: "Mueang Sukhothai", provinceCode: "64" },
  { code: "6402", nameTh: "บ้านด่านลานหอย", nameEn: "Ban Dan Lan Hoi", provinceCode: "64" },
  { code: "6403", nameTh: "คีรีมาศ", nameEn: "Khiri Mat", provinceCode: "64" },
  { code: "6404", nameTh: "กงไกรลาศ", nameEn: "Kong Krailat", provinceCode: "64" },
  { code: "6405", nameTh: "ศรีสัชนาลัย", nameEn: "Si Satchanalai", provinceCode: "64" },
  { code: "6406", nameTh: "ศรีสำโรง", nameEn: "Si Samrong", provinceCode: "64" },
  { code: "6407", nameTh: "สวรรคโลก", nameEn: "Sawankhalok", provinceCode: "64" },
  { code: "6408", nameTh: "ศรีนคร", nameEn: "Si Nakhon", provinceCode: "64" },
  { code: "6409", nameTh: "ทุ่งเสลี่ยม", nameEn: "Thung Saliam", provinceCode: "64" },
  { code: "6501", nameTh: "เมืองพิษณุโลก", nameEn: "Mueang Phitsanulok", provinceCode: "65" },
  { code: "6502", nameTh: "นครไทย", nameEn: "Nakhon Thai", provinceCode: "65" },
  { code: "6503", nameTh: "ชาติตระการ", nameEn: "Chat Trakan", provinceCode: "65" },
  { code: "6504", nameTh: "บางระกำ", nameEn: "Bang Rakam", provinceCode: "65" },
  { code: "6505", nameTh: "บางกระทุ่ม", nameEn: "Bang Krathum", provinceCode: "65" },
  { code: "6506", nameTh: "พรหมพิราม", nameEn: "Phrom Phiram", provinceCode: "65" },
  { code: "6507", nameTh: "วัดโบสถ์", nameEn: "Wat Bot", provinceCode: "65" },
  { code: "6508", nameTh: "วังทอง", nameEn: "Wang Thong", provinceCode: "65" },
  { code: "6509", nameTh: "เนินมะปราง", nameEn: "Noen Maprang", provinceCode: "65" },
  { code: "6601", nameTh: "เมืองพิจิตร", nameEn: "Mueang Phichit", provinceCode: "66" },
  { code: "6602", nameTh: "วังทรายพูน", nameEn: "Wang Sai Phun", provinceCode: "66" },
  { code: "6603", nameTh: "โพธิ์ประทับช้าง", nameEn: "Pho Prathap Chang", provinceCode: "66" },
  { code: "6604", nameTh: "ตะพานหิน", nameEn: "Taphan Hin", provinceCode: "66" },
  { code: "6605", nameTh: "บางมูลนาก", nameEn: "Bang Mun Nak", provinceCode: "66" },
  { code: "6606", nameTh: "โพทะเล", nameEn: "Pho Thale", provinceCode: "66" },
  { code: "6607", nameTh: "สามง่าม", nameEn: "Sam Ngam", provinceCode: "66" },
  { code: "6608", nameTh: "ทับคล้อ", nameEn: "Tap Khlo", provinceCode: "66" },
  { code: "6609", nameTh: "สากเหล็ก", nameEn: "Sak Lek", provinceCode: "66" },
  { code: "6610", nameTh: "บึงนาราง", nameEn: "Bueng Na Rang", provinceCode: "66" },
  { code: "6611", nameTh: "ดงเจริญ", nameEn: "Dong Charoen", provinceCode: "66" },
  { code: "6612", nameTh: "วชิรบารมี", nameEn: "Wachirabarami", provinceCode: "66" },
  { code: "6701", nameTh: "เมืองเพชรบูรณ์", nameEn: "Mueang Phetchabun", provinceCode: "67" },
  { code: "6702", nameTh: "ชนแดน", nameEn: "Chon Daen", provinceCode: "67" },
  { code: "6703", nameTh: "หล่มสัก", nameEn: "Lom Sak", provinceCode: "67" },
  { code: "6704", nameTh: "หล่มเก่า", nameEn: "Lom Kao", provinceCode: "67" },
  { code: "6705", nameTh: "วิเชียรบุรี", nameEn: "Wichian Buri", provinceCode: "67" },
  { code: "6706", nameTh: "ศรีเทพ", nameEn: "Si Thep", provinceCode: "67" },
  { code: "6707", nameTh: "หนองไผ่", nameEn: "Nong Phai", provinceCode: "67" },
  { code: "6708", nameTh: "บึงสามพัน", nameEn: "Bueng Sam Phan", provinceCode: "67" },
  { code: "6709", nameTh: "น้ำหนาว", nameEn: "Nam Nao", provinceCode: "67" },
  { code: "6710", nameTh: "วังโป่ง", nameEn: "Wang Pong", provinceCode: "67" },
  { code: "6711", nameTh: "เขาค้อ", nameEn: "Khao Kho", provinceCode: "67" },
  { code: "7001", nameTh: "เมืองราชบุรี", nameEn: "Mueang Ratchaburi", provinceCode: "70" },
  { code: "7002", nameTh: "จอมบึง", nameEn: "Chom Bueng", provinceCode: "70" },
  { code: "7003", nameTh: "สวนผึ้ง", nameEn: "Suan Phueng", provinceCode: "70" },
  { code: "7004", nameTh: "ดำเนินสะดวก", nameEn: "Damnoen Saduak", provinceCode: "70" },
  { code: "7005", nameTh: "บ้านโป่ง", nameEn: "Ban Pong", provinceCode: "70" },
  { code: "7006", nameTh: "บางแพ", nameEn: "Bang Phae", provinceCode: "70" },
  { code: "7007", nameTh: "โพธาราม", nameEn: "Photharam", provinceCode: "70" },
  { code: "7008", nameTh: "ปากท่อ", nameEn: "Pak Tho", provinceCode: "70" },
  { code: "7009", nameTh: "วัดเพลง", nameEn: "Wat Phleng", provinceCode: "70" },
  { code: "7010", nameTh: "บ้านคา", nameEn: "Ban Kha", provinceCode: "70" },
  { code: "7074", nameTh: "ท้องถิ่นเทศบาลตำบลบ้านฆ้อง", nameEn: "Tet Saban Ban Kong", provinceCode: "70" },
  { code: "7101", nameTh: "เมืองกาญจนบุรี", nameEn: "Mueang Kanchanaburi", provinceCode: "71" },
  { code: "7102", nameTh: "ไทรโยค", nameEn: "Sai Yok", provinceCode: "71" },
  { code: "7103", nameTh: "บ่อพลอย", nameEn: "Bo Phloi", provinceCode: "71" },
  { code: "7104", nameTh: "ศรีสวัสดิ์", nameEn: "Si Sawat", provinceCode: "71" },
  { code: "7105", nameTh: "ท่ามะกา", nameEn: "Tha Maka", provinceCode: "71" },
  { code: "7106", nameTh: "ท่าม่วง", nameEn: "Tha Muang", provinceCode: "71" },
  { code: "7107", nameTh: "ทองผาภูมิ", nameEn: "Pha Phum", provinceCode: "71" },
  { code: "7108", nameTh: "สังขละบุรี", nameEn: "Sangkhla Buri", provinceCode: "71" },
  { code: "7109", nameTh: "พนมทวน", nameEn: "Phanom Thuan", provinceCode: "71" },
  { code: "7110", nameTh: "เลาขวัญ", nameEn: "Lao Khwan", provinceCode: "71" },
  { code: "7111", nameTh: "ด่านมะขามเตี้ย", nameEn: "Dan Makham Tia", provinceCode: "71" },
  { code: "7112", nameTh: "หนองปรือ", nameEn: "Nong Prue", provinceCode: "71" },
  { code: "7113", nameTh: "ห้วยกระเจา", nameEn: "Huai Krachao", provinceCode: "71" },
  { code: "7201", nameTh: "เมืองสุพรรณบุรี", nameEn: "Mueang Suphan Buri", provinceCode: "72" },
  { code: "7202", nameTh: "เดิมบางนางบวช", nameEn: "Doem Bang Nang Buat", provinceCode: "72" },
  { code: "7203", nameTh: "ด่านช้าง", nameEn: "Dan Chang", provinceCode: "72" },
  { code: "7204", nameTh: "บางปลาม้า", nameEn: "Bang Pla Ma", provinceCode: "72" },
  { code: "7205", nameTh: "ศรีประจันต์", nameEn: "Si Prachan", provinceCode: "72" },
  { code: "7206", nameTh: "ดอนเจดีย์", nameEn: "Don Chedi", provinceCode: "72" },
  { code: "7207", nameTh: "สองพี่น้อง", nameEn: "Song Phi Nong", provinceCode: "72" },
  { code: "7208", nameTh: "สามชุก", nameEn: "Sam Chuk", provinceCode: "72" },
  { code: "7209", nameTh: "อู่ทอง", nameEn: "U Thong", provinceCode: "72" },
  { code: "7210", nameTh: "หนองหญ้าไซ", nameEn: "Nong Ya Sai", provinceCode: "72" },
  { code: "7301", nameTh: "เมืองนครปฐม", nameEn: "Mueang Nakhon Pathom", provinceCode: "73" },
  { code: "7302", nameTh: "กำแพงแสน", nameEn: "Kamphaeng Saen", provinceCode: "73" },
  { code: "7303", nameTh: "นครชัยศรี", nameEn: "Nakhon Chai Si", provinceCode: "73" },
  { code: "7304", nameTh: "ดอนตูม", nameEn: "Don Tum", provinceCode: "73" },
  { code: "7305", nameTh: "บางเลน", nameEn: "Bang Len", provinceCode: "73" },
  { code: "7306", nameTh: "สามพราน", nameEn: "Sam Phran", provinceCode: "73" },
  { code: "7307", nameTh: "พุทธมณฑล", nameEn: "Phutthamonthon", provinceCode: "73" },
  { code: "7401", nameTh: "เมืองสมุทรสาคร", nameEn: "Mueang Samut Sakhon", provinceCode: "74" },
  { code: "7402", nameTh: "กระทุ่มแบน", nameEn: "Krathum Baen", provinceCode: "74" },
  { code: "7403", nameTh: "บ้านแพ้ว", nameEn: "Ban Phaeo", provinceCode: "74" },
  { code: "7501", nameTh: "เมืองสมุทรสงคราม", nameEn: "Mueang Samut Songkhram", provinceCode: "75" },
  { code: "7502", nameTh: "บางคนที", nameEn: "Bang Khonthi", provinceCode: "75" },
  { code: "7503", nameTh: "อัมพวา", nameEn: "Amphawa", provinceCode: "75" },
  { code: "7601", nameTh: "เมืองเพชรบุรี", nameEn: "Mueang Phetchaburi", provinceCode: "76" },
  { code: "7602", nameTh: "เขาย้อย", nameEn: "Khao Yoi", provinceCode: "76" },
  { code: "7603", nameTh: "หนองหญ้าปล้อง", nameEn: "Nong Ya Plong", provinceCode: "76" },
  { code: "7604", nameTh: "ชะอำ", nameEn: "Cha-am", provinceCode: "76" },
  { code: "7605", nameTh: "ท่ายาง", nameEn: "Tha Yang", provinceCode: "76" },
  { code: "7606", nameTh: "บ้านลาด", nameEn: "Ban Lat", provinceCode: "76" },
  { code: "7607", nameTh: "บ้านแหลม", nameEn: "Ban Laem", provinceCode: "76" },
  { code: "7608", nameTh: "แก่งกระจาน", nameEn: "Kaeng Krachan", provinceCode: "76" },
  { code: "7701", nameTh: "เมืองประจวบคีรีขันธ์", nameEn: "Mueang Prachuap Khiri Khan", provinceCode: "77" },
  { code: "7702", nameTh: "กุยบุรี", nameEn: "Kui Buri", provinceCode: "77" },
  { code: "7703", nameTh: "ทับสะแก", nameEn: "Thap Sakae", provinceCode: "77" },
  { code: "7704", nameTh: "บางสะพาน", nameEn: "Bang Saphan", provinceCode: "77" },
  { code: "7705", nameTh: "บางสะพานน้อย", nameEn: "Bang Saphan Noi", provinceCode: "77" },
  { code: "7706", nameTh: "ปราณบุรี", nameEn: "Pran Buri", provinceCode: "77" },
  { code: "7707", nameTh: "หัวหิน", nameEn: "Hua Hin", provinceCode: "77" },
  { code: "7708", nameTh: "สามร้อยยอด", nameEn: "Sam Roi Yot", provinceCode: "77" },
  { code: "8001", nameTh: "เมืองนครศรีธรรมราช", nameEn: "Mueang Nakhon Si Thammarat", provinceCode: "80" },
  { code: "8002", nameTh: "พรหมคีรี", nameEn: "Phrom Khiri", provinceCode: "80" },
  { code: "8003", nameTh: "ลานสกา", nameEn: "Lan Saka", provinceCode: "80" },
  { code: "8004", nameTh: "ฉวาง", nameEn: "Chawang", provinceCode: "80" },
  { code: "8005", nameTh: "พิปูน", nameEn: "Phipun", provinceCode: "80" },
  { code: "8006", nameTh: "เชียรใหญ่", nameEn: "Chian Yai", provinceCode: "80" },
  { code: "8007", nameTh: "ชะอวด", nameEn: "Cha-uat", provinceCode: "80" },
  { code: "8008", nameTh: "ท่าศาลา", nameEn: "Tha Sala", provinceCode: "80" },
  { code: "8009", nameTh: "ทุ่งสง", nameEn: "Thung Song", provinceCode: "80" },
  { code: "8010", nameTh: "นาบอน", nameEn: "Na Bon", provinceCode: "80" },
  { code: "8011", nameTh: "ทุ่งใหญ่", nameEn: "Thung Yai", provinceCode: "80" },
  { code: "8012", nameTh: "ปากพนัง", nameEn: "Pak Phanang", provinceCode: "80" },
  { code: "8013", nameTh: "ร่อนพิบูลย์", nameEn: "Ron Phibun", provinceCode: "80" },
  { code: "8014", nameTh: "สิชล", nameEn: "Sichon", provinceCode: "80" },
  { code: "8015", nameTh: "ขนอม", nameEn: "Khanom", provinceCode: "80" },
  { code: "8016", nameTh: "หัวไทร", nameEn: "Hua Sai", provinceCode: "80" },
  { code: "8017", nameTh: "บางขัน", nameEn: "Bang Khan", provinceCode: "80" },
  { code: "8018", nameTh: "ถ้ำพรรณรา", nameEn: "Tham Phannara", provinceCode: "80" },
  { code: "8019", nameTh: "จุฬาภรณ์", nameEn: "Chulabhorn", provinceCode: "80" },
  { code: "8020", nameTh: "พระพรหม", nameEn: "Phra Phrom", provinceCode: "80" },
  { code: "8021", nameTh: "นบพิตำ", nameEn: "Nopphitam", provinceCode: "80" },
  { code: "8022", nameTh: "ช้างกลาง", nameEn: "Chang Klang", provinceCode: "80" },
  { code: "8023", nameTh: "เฉลิมพระเกียรติ", nameEn: "Chaloem Phra Kiat", provinceCode: "80" },
  { code: "8101", nameTh: "เมืองกระบี่", nameEn: "Mueang Krabi", provinceCode: "81" },
  { code: "8102", nameTh: "เขาพนม", nameEn: "Khao Phanom", provinceCode: "81" },
  { code: "8103", nameTh: "เกาะลันตา", nameEn: "Ko Lanta", provinceCode: "81" },
  { code: "8104", nameTh: "คลองท่อม", nameEn: "Khlong Thom", provinceCode: "81" },
  { code: "8105", nameTh: "อ่าวลึก", nameEn: "Ao Luek", provinceCode: "81" },
  { code: "8106", nameTh: "ปลายพระยา", nameEn: "Plai Phraya", provinceCode: "81" },
  { code: "8107", nameTh: "ลำทับ", nameEn: "Lam Thap", provinceCode: "81" },
  { code: "8108", nameTh: "เหนือคลอง", nameEn: "Nuea Khlong", provinceCode: "81" },
  { code: "8201", nameTh: "เมืองพังงา", nameEn: "Mueang Phang-nga", provinceCode: "82" },
  { code: "8202", nameTh: "เกาะยาว", nameEn: "Ko Yao", provinceCode: "82" },
  { code: "8203", nameTh: "กะปง", nameEn: "Kapong", provinceCode: "82" },
  { code: "8204", nameTh: "ตะกั่วทุ่ง", nameEn: "Takua Thung", provinceCode: "82" },
  { code: "8205", nameTh: "ตะกั่วป่า", nameEn: "Takua Pa", provinceCode: "82" },
  { code: "8206", nameTh: "คุระบุรี", nameEn: "Khura Buri", provinceCode: "82" },
  { code: "8207", nameTh: "ทับปุด", nameEn: "Thap Put", provinceCode: "82" },
  { code: "8208", nameTh: "ท้ายเหมือง", nameEn: "Thai Mueang", provinceCode: "82" },
  { code: "8301", nameTh: "เมืองภูเก็ต", nameEn: "Mueang Phuket", provinceCode: "83" },
  { code: "8302", nameTh: "กะทู้", nameEn: "Kathu", provinceCode: "83" },
  { code: "8303", nameTh: "ถลาง", nameEn: "Thalang", provinceCode: "83" },
  { code: "8401", nameTh: "เมืองสุราษฎร์ธานี", nameEn: "Mueang Surat Thani", provinceCode: "84" },
  { code: "8402", nameTh: "กาญจนดิษฐ์", nameEn: "Kanchanadit", provinceCode: "84" },
  { code: "8403", nameTh: "ดอนสัก", nameEn: "Don Sak", provinceCode: "84" },
  { code: "8404", nameTh: "เกาะสมุย", nameEn: "Ko Samui", provinceCode: "84" },
  { code: "8405", nameTh: "เกาะพะงัน", nameEn: "Ko Pha-ngan", provinceCode: "84" },
  { code: "8406", nameTh: "ไชยา", nameEn: "Chaiya", provinceCode: "84" },
  { code: "8407", nameTh: "ท่าชนะ", nameEn: "Tha Chana", provinceCode: "84" },
  { code: "8408", nameTh: "คีรีรัฐนิคม", nameEn: "Khiri Rat Nikhom", provinceCode: "84" },
  { code: "8409", nameTh: "บ้านตาขุน", nameEn: "Ban Ta Khun", provinceCode: "84" },
  { code: "8410", nameTh: "พนม", nameEn: "Phanom", provinceCode: "84" },
  { code: "8411", nameTh: "ท่าฉาง", nameEn: "Tha Chang", provinceCode: "84" },
  { code: "8412", nameTh: "บ้านนาสาร", nameEn: "Ban Na San", provinceCode: "84" },
  { code: "8413", nameTh: "บ้านนาเดิม", nameEn: "Ban Na Doem", provinceCode: "84" },
  { code: "8414", nameTh: "เคียนซา", nameEn: "Khian Sa", provinceCode: "84" },
  { code: "8415", nameTh: "เวียงสระ", nameEn: "Wiang Sa", provinceCode: "84" },
  { code: "8416", nameTh: "พระแสง", nameEn: "Phrasaeng", provinceCode: "84" },
  { code: "8417", nameTh: "พุนพิน", nameEn: "Phunphin", provinceCode: "84" },
  { code: "8418", nameTh: "ชัยบุรี", nameEn: "Chai Buri", provinceCode: "84" },
  { code: "8419", nameTh: "วิภาวดี", nameEn: "Vibhavadi", provinceCode: "84" },
  { code: "8501", nameTh: "เมืองระนอง", nameEn: "Mueang Ranong", provinceCode: "85" },
  { code: "8502", nameTh: "ละอุ่น", nameEn: "La-un", provinceCode: "85" },
  { code: "8503", nameTh: "กะเปอร์", nameEn: "Kapoe", provinceCode: "85" },
  { code: "8504", nameTh: "กระบุรี", nameEn: "Kra Buri", provinceCode: "85" },
  { code: "8505", nameTh: "สุขสำราญ", nameEn: "Suk Samran", provinceCode: "85" },
  { code: "8601", nameTh: "เมืองชุมพร", nameEn: "Mueang Chumphon", provinceCode: "86" },
  { code: "8602", nameTh: "ท่าแซะ", nameEn: "Tha Sae", provinceCode: "86" },
  { code: "8603", nameTh: "ปะทิว", nameEn: "Pathio", provinceCode: "86" },
  { code: "8604", nameTh: "หลังสวน", nameEn: "Lang Suan", provinceCode: "86" },
  { code: "8605", nameTh: "ละแม", nameEn: "Lamae", provinceCode: "86" },
  { code: "8606", nameTh: "พะโต๊ะ", nameEn: "Phato", provinceCode: "86" },
  { code: "8607", nameTh: "สวี", nameEn: "Sawi", provinceCode: "86" },
  { code: "8608", nameTh: "ทุ่งตะโก", nameEn: "Thung Tako", provinceCode: "86" },
  { code: "9001", nameTh: "เมืองสงขลา", nameEn: "Mueang Songkhla", provinceCode: "90" },
  { code: "9002", nameTh: "สทิงพระ", nameEn: "Sathing Phra", provinceCode: "90" },
  { code: "9003", nameTh: "จะนะ", nameEn: "Chana", provinceCode: "90" },
  { code: "9004", nameTh: "นาทวี", nameEn: "Na Thawi", provinceCode: "90" },
  { code: "9005", nameTh: "เทพา", nameEn: "Thepha", provinceCode: "90" },
  { code: "9006", nameTh: "สะบ้าย้อย", nameEn: "Saba Yoi", provinceCode: "90" },
  { code: "9007", nameTh: "ระโนด", nameEn: "Ranot", provinceCode: "90" },
  { code: "9008", nameTh: "กระแสสินธุ์", nameEn: "Krasae Sin", provinceCode: "90" },
  { code: "9009", nameTh: "รัตภูมิ", nameEn: "Rattaphum", provinceCode: "90" },
  { code: "9010", nameTh: "สะเดา", nameEn: "Sadao", provinceCode: "90" },
  { code: "9011", nameTh: "หาดใหญ่", nameEn: "Hat Yai", provinceCode: "90" },
  { code: "9012", nameTh: "นาหม่อม", nameEn: "Na Mom", provinceCode: "90" },
  { code: "9013", nameTh: "ควนเนียง", nameEn: "Khuan Niang", provinceCode: "90" },
  { code: "9014", nameTh: "บางกล่ำ", nameEn: "Bang Klam", provinceCode: "90" },
  { code: "9015", nameTh: "สิงหนคร", nameEn: "Singhanakhon", provinceCode: "90" },
  { code: "9016", nameTh: "คลองหอยโข่ง", nameEn: "Khlong Hoi Khong", provinceCode: "90" },
  { code: "9077", nameTh: "ท้องถิ่นเทศบาลตำบลสำนักขาม", nameEn: "Sum Nung Kam", provinceCode: "90" },
  { code: "9101", nameTh: "เมืองสตูล", nameEn: "Mueang Satun", provinceCode: "91" },
  { code: "9102", nameTh: "ควนโดน", nameEn: "Khuan Don", provinceCode: "91" },
  { code: "9103", nameTh: "ควนกาหลง", nameEn: "Khuan Kalong", provinceCode: "91" },
  { code: "9104", nameTh: "ท่าแพ", nameEn: "Tha Phae", provinceCode: "91" },
  { code: "9105", nameTh: "ละงู", nameEn: "La-ngu", provinceCode: "91" },
  { code: "9106", nameTh: "ทุ่งหว้า", nameEn: "Thung Wa", provinceCode: "91" },
  { code: "9107", nameTh: "มะนัง", nameEn: "Manang", provinceCode: "91" },
  { code: "9201", nameTh: "เมืองตรัง", nameEn: "Mueang Trang", provinceCode: "92" },
  { code: "9202", nameTh: "กันตัง", nameEn: "Kantang", provinceCode: "92" },
  { code: "9203", nameTh: "ย่านตาขาว", nameEn: "Yan Ta Khao", provinceCode: "92" },
  { code: "9204", nameTh: "ปะเหลียน", nameEn: "Palian", provinceCode: "92" },
  { code: "9205", nameTh: "สิเกา", nameEn: "Sikao", provinceCode: "92" },
  { code: "9206", nameTh: "ห้วยยอด", nameEn: "Huai Yot", provinceCode: "92" },
  { code: "9207", nameTh: "วังวิเศษ", nameEn: "Wang Wiset", provinceCode: "92" },
  { code: "9208", nameTh: "นาโยง", nameEn: "Na Yong", provinceCode: "92" },
  { code: "9209", nameTh: "รัษฎา", nameEn: "Ratsada", provinceCode: "92" },
  { code: "9210", nameTh: "หาดสำราญ", nameEn: "Hat Samran", provinceCode: "92" },
  { code: "9301", nameTh: "เมืองพัทลุง", nameEn: "Mueang Phatthalung", provinceCode: "93" },
  { code: "9302", nameTh: "กงหรา", nameEn: "Kong Ra", provinceCode: "93" },
  { code: "9303", nameTh: "เขาชัยสน", nameEn: "Khao Chaison", provinceCode: "93" },
  { code: "9304", nameTh: "ตะโหมด", nameEn: "Tamot", provinceCode: "93" },
  { code: "9305", nameTh: "ควนขนุน", nameEn: "Khuan Khanun", provinceCode: "93" },
  { code: "9306", nameTh: "ปากพะยูน", nameEn: "Pak Phayun", provinceCode: "93" },
  { code: "9307", nameTh: "ศรีบรรพต", nameEn: "Si Banphot", provinceCode: "93" },
  { code: "9308", nameTh: "ป่าบอน", nameEn: "Pa Bon", provinceCode: "93" },
  { code: "9309", nameTh: "บางแก้ว", nameEn: "Bang Kaeo", provinceCode: "93" },
  { code: "9310", nameTh: "ป่าพะยอม", nameEn: "Pa Phayom", provinceCode: "93" },
  { code: "9311", nameTh: "ศรีนครินทร์", nameEn: "Srinagarindra", provinceCode: "93" },
  { code: "9401", nameTh: "เมืองปัตตานี", nameEn: "Mueang Pattani", provinceCode: "94" },
  { code: "9402", nameTh: "โคกโพธิ์", nameEn: "Khok Pho", provinceCode: "94" },
  { code: "9403", nameTh: "หนองจิก", nameEn: "Nong Chik", provinceCode: "94" },
  { code: "9404", nameTh: "ปะนาเระ", nameEn: "Panare", provinceCode: "94" },
  { code: "9405", nameTh: "มายอ", nameEn: "Mayo", provinceCode: "94" },
  { code: "9406", nameTh: "ทุ่งยางแดง", nameEn: "Thung Yang Daeng", provinceCode: "94" },
  { code: "9407", nameTh: "สายบุรี", nameEn: "Sai Buri", provinceCode: "94" },
  { code: "9408", nameTh: "ไม้แก่น", nameEn: "Mai Kaen", provinceCode: "94" },
  { code: "9409", nameTh: "ยะหริ่ง", nameEn: "Yaring", provinceCode: "94" },
  { code: "9410", nameTh: "ยะรัง", nameEn: "Yarang", provinceCode: "94" },
  { code: "9411", nameTh: "กะพ้อ", nameEn: "Kapho", provinceCode: "94" },
  { code: "9412", nameTh: "แม่ลาน", nameEn: "Mae Lan", provinceCode: "94" },
  { code: "9501", nameTh: "เมืองยะลา", nameEn: "Mueang Yala", provinceCode: "95" },
  { code: "9502", nameTh: "เบตง", nameEn: "Betong", provinceCode: "95" },
  { code: "9503", nameTh: "บันนังสตา", nameEn: "Bannang Sata", provinceCode: "95" },
  { code: "9504", nameTh: "ธารโต", nameEn: "Than To", provinceCode: "95" },
  { code: "9505", nameTh: "ยะหา", nameEn: "Yaha", provinceCode: "95" },
  { code: "9506", nameTh: "รามัน", nameEn: "Raman", provinceCode: "95" },
  { code: "9507", nameTh: "กาบัง", nameEn: "Kabang", provinceCode: "95" },
  { code: "9508", nameTh: "กรงปินัง", nameEn: "Krong Pinang", provinceCode: "95" },
  { code: "9601", nameTh: "เมืองนราธิวาส", nameEn: "Mueang Narathiwat", provinceCode: "96" },
  { code: "9602", nameTh: "ตากใบ", nameEn: "Tak Bai", provinceCode: "96" },
  { code: "9603", nameTh: "บาเจาะ", nameEn: "Bacho", provinceCode: "96" },
  { code: "9604", nameTh: "ยี่งอ", nameEn: "Yi-ngo", provinceCode: "96" },
  { code: "9605", nameTh: "ระแงะ", nameEn: "Ra-ngae", provinceCode: "96" },
  { code: "9606", nameTh: "รือเสาะ", nameEn: "Rueso", provinceCode: "96" },
  { code: "9607", nameTh: "ศรีสาคร", nameEn: "Si Sakhon", provinceCode: "96" },
  { code: "9608", nameTh: "แว้ง", nameEn: "Waeng", provinceCode: "96" },
  { code: "9609", nameTh: "สุคิริน", nameEn: "Sukhirin", provinceCode: "96" },
  { code: "9610", nameTh: "สุไหงโก-ลก", nameEn: "Su-ngai Kolok", provinceCode: "96" },
  { code: "9611", nameTh: "สุไหงปาดี", nameEn: "Su-ngai Padi", provinceCode: "96" },
  { code: "9612", nameTh: "จะแนะ", nameEn: "Chanae", provinceCode: "96" },
  { code: "9613", nameTh: "เจาะไอร้อง", nameEn: "Cho-airong", provinceCode: "96" },
];
